export type Lang = 'en' | 'bn';

const en = {
  appName: 'Sonic Earth Atlas',
  tagline: 'An Earth Information Jukebox',
  heroLead: 'Real NASA Earth observations and NASA imagery, played as sound. Pick a track, put on headphones, and listen to where the planet is burning, raining and warming.',
  heroNote: 'Every sound is generated live from the data. Nothing is pre-recorded.',
  heroHeadphones: 'Headphones help: left and right follow longitude.',
  pickTrack: 'Pick a track',
  listenNow: 'Listen now',
  audioBlocked: 'Your browser blocked the sound. Press Play again, check the volume, and turn off silent mode.',
  tryEic: 'Play a bundled Earth Information Center frame instead',
  startTour: 'Play the 40-second tour',
  exploreSilently: 'Explore without sound',
  track1: 'Planet this week',
  track1Desc: 'Fires, rain and ocean heat from 2–5 October 2026, placed around you in stereo.',
  track2: 'EIC frames + NASA imagery',
  track2Desc: 'NASA Earth Information Center visuals and satellite images of the same days, swept left to right and turned into sound.',
  track3: 'Bangladesh monsoon',
  track3Desc: 'Daily rain in 8 divisions, June to October 2026, against 2025 and the 20-year normal.',
  track4: "Earth's vital signs",
  track4Desc: 'Global temperature since 1880, CO₂ since 1959 and Arctic sea ice since 1979, one note per year, alone or as one chord. Or play your own CSV.',
  anyPlace: 'Any place',
  tracks: 'Tracks',
  globe: 'Globe',
  map: 'Map',
  list: 'List',
  soundOn: 'Sound on',
  soundOff: 'Sound off',
  tour: 'Tour',
  data: 'Data & method',
  settings: 'Settings',
  home: 'Home',
  layers: 'Layers',
  fire: 'Wildfires',
  rain: 'Rain',
  ocean: 'Ocean heat',
  fireUnit: 'fire power, MW',
  rainUnit: 'daily rain, mm',
  oceanUnit: 'SST anomaly, °C',
  fireSound: 'crackle',
  rainSound: 'droplets',
  oceanSound: 'drone',
  hear: 'Hear',
  nowHearing: 'What you are hearing',
  nothingPlaying: 'Turn sound on to hear the data. Each voice below is one real observation.',
  loudest: 'Loudest voices right now',
  left: 'left',
  right: 'right',
  centre: 'centre',
  rising: 'rising',
  falling: 'easing',
  steady: 'steady',
  vsYesterday: 'vs day before',
  pitch: 'pitch',
  rate: 'pulses/s',
  pan: 'position',
  hearChange: 'Hear the change',
  hearChangeHint: 'Louder and faster where values grew since the day before',
  play: 'Play',
  legend: 'Legend',
  loudness: 'Loudness',
  whatHearing: 'What am I hearing?',
  hearNeedle: 'The needle is the vertical line. It moves west to east, left to right, and you hear the column of the picture under it.',
  hearPitch: 'Height is pitch: the top of the picture is the highest note, the bottom the lowest. There are 12 bands.',
  hearLoud: 'Brightness is loudness: bright pixels are loud, dark pixels are silent.',
  hearColour: 'Colour is timbre: warm reds and oranges buzz, blues and greens stay soft.',
  hearScrub: 'Drag the needle slider, or click the picture, to hear any single spot. Drag across the picture to loop one part.',
  scrub: 'Needle position',
  scrubHint: 'Drag, or use the arrow keys, to hear any part of the picture. Click or tap the picture to hear that spot.',
  loop: 'Loop',
  speed: 'Speed',
  loopStart: 'Loop starts here',
  loopEnd: 'Loop ends here',
  clearRegion: 'Whole picture',
  regionHint: 'Drag across the picture to loop just that part.',
  pause: 'Pause',
  prevDay: 'Previous day',
  nextDay: 'Next day',
  record: 'Record 30 s',
  recording: 'Recording… {s}s',
  recordSaved: 'Saved {name}',
  language: 'Language',
  reduceMotion: 'Reduce motion',
  highContrast: 'High contrast',
  narration: 'Spoken narration',
  spatial: 'Spatial audio',
  stereo: 'Stereo',
  hrtf: '3D (HRTF)',
  volume: 'Volume',
  shortcuts: 'Keyboard shortcuts',
  close: 'Close',
  realData: 'Real NASA data',
  sampleFallback: 'Offline sample (real snapshots could not load)',
  bdLens: 'Bangladesh',
  monsoonTitle: 'Bangladesh monsoon 2026',
  monsoonLead: 'Each division is a voice. West is left, east is right, north is higher. Heavier rain means denser, louder droplets.',
  compare2025: 'Compare with 2025',
  totalSince: 'Total since 1 June',
  ofNormal: 'of the 2001–2020 normal',
  wettest: 'Wettest day',
  pulseTitle: '146 years of global warming',
  pulseLead: 'One note per year. Higher pitch means a warmer planet compared with 1951–1980.',
  framesTitle: 'Earth Information Center frames',
  framesLead: 'A needle sweeps each NASA Earth Information Center frame or satellite image from west to east. Height is pitch, brightness is loudness, colour is timbre.',
  beforeAfter: 'Before / after',
  beforeAfterHint: 'Left ear plays the first image, right ear the second, at the same moment.',
  loadOwn: 'Load your own EIC image',
  eicGroup: 'NASA Earth Information Center (earth.gov)',
  imagery: 'NASA imagery',
  imageryHint: 'Show NASA satellite imagery of the selected day on the globe',
  dataFrom: 'Data from',
  listenHere: 'Listen here',
  noObs: 'No observation in the loaded data here.',
  skip: 'Skip to main content',
};

export type StringKey = keyof typeof en;

const bn: Partial<Record<StringKey, string>> = {
  appName: 'সনিক আর্থ অ্যাটলাস',
  tagline: 'পৃথিবীর তথ্যের জুকবক্স',
  heroLead: 'নাসার আসল পৃথিবী পর্যবেক্ষণ আর স্যাটেলাইট ছবি, শব্দ হয়ে বাজে। একটা ট্র্যাক বেছে নিন, হেডফোন পরুন, শুনুন কোথায় আগুন জ্বলছে, বৃষ্টি হচ্ছে, সমুদ্র গরম হচ্ছে।',
  heroNote: 'প্রতিটি শব্দ ডেটা থেকে সরাসরি তৈরি হয়। কিছুই আগে থেকে রেকর্ড করা নয়।',
  heroHeadphones: 'হেডফোন ভালো: বাম-ডান শব্দ দ্রাঘিমাংশ অনুসরণ করে।',
  pickTrack: 'একটা ট্র্যাক বাছুন',
  startTour: '৪০ সেকেন্ডের ট্যুর চালান',
  listenNow: 'এখনই শুনুন',
  audioBlocked: 'আপনার ব্রাউজার শব্দ আটকে দিয়েছে। আবার চালান চাপুন, ভলিউম দেখুন আর সাইলেন্ট মোড বন্ধ করুন।',
  tryEic: 'এর বদলে সাথে থাকা একটি আর্থ ইনফরমেশন সেন্টার ফ্রেম চালান',
  exploreSilently: 'শব্দ ছাড়া দেখুন',
  track1: 'এই সপ্তাহের পৃথিবী',
  track1Desc: '২–৫ অক্টোবর ২০২৬-এর আগুন, বৃষ্টি আর সমুদ্রের তাপ, আপনার চারপাশে স্টেরিওতে।',
  track2: 'EIC ফ্রেম ও নাসার ছবি',
  track2Desc: 'নাসার আর্থ ইনফরমেশন সেন্টারের ছবি ও একই দিনের স্যাটেলাইট ছবি, বাম থেকে ডানে স্ক্যান হয়ে শব্দ হয়।',
  track3: 'বাংলাদেশের বর্ষা',
  track3Desc: '৮ বিভাগের দৈনিক বৃষ্টি, জুন–অক্টোবর ২০২৬, ২০২৫ আর ২০ বছরের গড়ের সাথে।',
  track4: 'পৃথিবীর প্রাণচিহ্ন',
  track4Desc: '১৮৮০ থেকে বৈশ্বিক তাপমাত্রা, ১৯৫৯ থেকে CO₂, ১৯৭৯ থেকে আর্কটিক বরফ, প্রতি বছর একটি সুর, আলাদা বা একসাথে। নিজের CSV-ও বাজাতে পারেন।',
  anyPlace: 'যেকোনো জায়গা',
  tracks: 'ট্র্যাক',
  globe: 'গ্লোব',
  map: 'মানচিত্র',
  list: 'তালিকা',
  soundOn: 'শব্দ চালু',
  soundOff: 'শব্দ বন্ধ',
  tour: 'ট্যুর',
  data: 'ডেটা ও পদ্ধতি',
  settings: 'সেটিংস',
  home: 'হোম',
  layers: 'স্তর',
  fire: 'দাবানল',
  rain: 'বৃষ্টি',
  ocean: 'সমুদ্রের তাপ',
  fireUnit: 'আগুনের শক্তি, মেগাওয়াট',
  rainUnit: 'দৈনিক বৃষ্টি, মিমি',
  oceanUnit: 'তাপমাত্রার বিচ্যুতি, °সে',
  fireSound: 'চটচট শব্দ',
  rainSound: 'ফোঁটা',
  oceanSound: 'গুঞ্জন',
  hear: 'শুনুন',
  nowHearing: 'আপনি কী শুনছেন',
  nothingPlaying: 'ডেটা শুনতে শব্দ চালু করুন। নিচের প্রতিটি কণ্ঠ একটি আসল পর্যবেক্ষণ।',
  loudest: 'এখন সবচেয়ে জোরালো',
  left: 'বামে',
  right: 'ডানে',
  centre: 'মাঝে',
  rising: 'বাড়ছে',
  falling: 'কমছে',
  steady: 'স্থির',
  vsYesterday: 'আগের দিনের তুলনায়',
  pitch: 'সুর',
  rate: 'স্পন্দন/সে',
  pan: 'অবস্থান',
  hearChange: 'পরিবর্তন শুনুন',
  hearChangeHint: 'আগের দিনের চেয়ে যেখানে বেড়েছে সেখানে শব্দ জোরালো ও দ্রুত',
  play: 'চালান',
  legend: 'নির্দেশিকা',
  loudness: 'জোর',
  whatHearing: 'আমি কী শুনছি?',
  hearNeedle: 'সুই হলো খাড়া দাগ। এটি পশ্চিম থেকে পূর্বে, বাম থেকে ডানে যায়, আর তার নিচের ছবির অংশের শব্দ শোনা যায়।',
  hearPitch: 'উচ্চতা মানে সুর: ছবির উপরের অংশে সবচেয়ে চড়া সুর, নিচে সবচেয়ে খাদ। মোট ১২টি স্তর।',
  hearLoud: 'উজ্জ্বলতা মানে জোর: উজ্জ্বল পিক্সেল জোরে, গাঢ় পিক্সেল নীরব।',
  hearColour: 'রং মানে ধ্বনির ধরন: লাল-কমলা ঝাঁঝালো, নীল-সবুজ নরম।',
  hearScrub: 'সুইয়ের স্লাইডার টানুন বা ছবিতে ক্লিক করুন, যেকোনো একটি জায়গার শব্দ শুনতে। ছবির উপর টেনে একটি অংশ বারবার শুনুন।',
  scrub: 'সুইয়ের অবস্থান',
  scrubHint: 'টেনে বা অ্যারো কী দিয়ে ছবির যেকোনো অংশ শুনুন। ছবিতে ক্লিক বা ট্যাপ করলে সেই জায়গার শব্দ শোনা যাবে।',
  loop: 'বারবার',
  speed: 'গতি',
  loopStart: 'এখান থেকে শুরু',
  loopEnd: 'এখানে শেষ',
  clearRegion: 'পুরো ছবি',
  regionHint: 'ছবির উপর টেনে শুধু সেই অংশ বারবার শুনুন।',
  pause: 'থামান',
  prevDay: 'আগের দিন',
  nextDay: 'পরের দিন',
  record: '৩০ সেকেন্ড রেকর্ড',
  recording: 'রেকর্ড হচ্ছে… {s} সে',
  recordSaved: '{name} সংরক্ষিত',
  language: 'ভাষা',
  reduceMotion: 'কম অ্যানিমেশন',
  highContrast: 'উচ্চ কনট্রাস্ট',
  narration: 'কণ্ঠে বর্ণনা',
  spatial: 'স্থানিক শব্দ',
  stereo: 'স্টেরিও',
  hrtf: '৩ডি (HRTF)',
  volume: 'ভলিউম',
  shortcuts: 'কিবোর্ড শর্টকাট',
  close: 'বন্ধ',
  realData: 'নাসার আসল ডেটা',
  bdLens: 'বাংলাদেশ',
  monsoonTitle: 'বাংলাদেশের বর্ষা ২০২৬',
  monsoonLead: 'প্রতিটি বিভাগ একটি কণ্ঠ। পশ্চিম বামে, পূর্ব ডানে, উত্তর উঁচু সুরে। বেশি বৃষ্টি মানে ঘন ও জোরালো ফোঁটা।',
  compare2025: '২০২৫-এর সাথে তুলনা',
  totalSince: '১ জুন থেকে মোট',
  ofNormal: '২০০১–২০২০ গড়ের',
  wettest: 'সবচেয়ে ভেজা দিন',
  pulseTitle: '১৪৬ বছরের বৈশ্বিক উষ্ণায়ন',
  pulseLead: 'প্রতি বছর একটি সুর। ১৯৫১–১৯৮০-র তুলনায় পৃথিবী যত গরম, সুর তত উঁচু।',
  framesTitle: 'আর্থ ইনফরমেশন সেন্টারের ফ্রেম',
  framesLead: 'একটি সুই নাসার স্যাটেলাইট ছবি পশ্চিম থেকে পূর্বে স্ক্যান করে। উচ্চতা = সুর, উজ্জ্বলতা = জোর, রং = ধ্বনির ধরন।',
  beforeAfter: 'আগে / পরে',
  beforeAfterHint: 'বাম কানে প্রথম ছবি, ডান কানে দ্বিতীয় ছবি, একই সময়ে।',
  loadOwn: 'নিজের EIC ছবি দিন',
  eicGroup: 'নাসা আর্থ ইনফরমেশন সেন্টার (earth.gov)',
  imagery: 'নাসার ছবি',
  imageryHint: 'নির্বাচিত দিনের নাসার স্যাটেলাইট ছবি গ্লোবে দেখান',
  dataFrom: 'ডেটার উৎস',
  listenHere: 'এখানে শুনুন',
  noObs: 'এখানে লোড করা ডেটায় কোনো পর্যবেক্ষণ নেই।',
  skip: 'মূল অংশে যান',
};

export const STRINGS: Record<Lang, Partial<Record<StringKey, string>>> = { en, bn };
