export type Lang = 'en' | 'bn';

const en = {
  appName: 'Sonic Earth Atlas',
  tagline: 'An Earth Information Jukebox',
  heroLead: 'Real NASA Earth observations and NASA imagery, played as sound. Pick a track, put on headphones, and listen to where the planet is burning, raining and warming.',
  heroNote: 'Every sound is generated live from the data. Nothing is pre-recorded.',
  heroHeadphones: 'Headphones help: left and right follow longitude.',
  pickTrack: 'Pick a track',
  listenNow: 'Listen now',
  audioBlocked: 'Your browser blocked the sound. Press Play again, check the volume, and turn off silent mode.',
  tryEic: 'Play a bundled Earth Information Center frame instead',
  startTour: 'Play the 40-second tour',
  exploreSilently: 'Explore without sound',
  track1: 'Planet this week',
  track1Desc: 'Fires, rain and ocean heat from 2–5 October 2026, placed around you in stereo.',
  track2: 'EIC frames + NASA imagery',
  track2Desc: 'NASA Earth Information Center visuals and satellite images of the same days, swept left to right and turned into sound.',
  track3: 'Bangladesh monsoon',
  track3Desc: 'Daily rain in 8 divisions, June to October 2026, against 2025 and the 20-year normal.',
  track4: "Earth's vital signs",
  track4Desc: 'Global temperature since 1880, CO₂ since 1959 and Arctic sea ice since 1979, one note per year, alone or as one chord. Or play your own CSV.',
  anyPlace: 'Any place',
  tracks: 'Tracks',
  globe: 'Globe',
  map: 'Map',
  list: 'List',
  soundOn: 'Sound on',
  soundOff: 'Sound off',
  tour: 'Tour',
  data: 'Data & method',
  settings: 'Settings',
  home: 'Home',
  layers: 'Layers',
  fire: 'Wildfires',
  rain: 'Rain',
  ocean: 'Ocean heat',
  fireUnit: 'fire power, MW',
  rainUnit: 'daily rain, mm',
  oceanUnit: 'SST anomaly, °C',
  fireSound: 'crackle',
  rainSound: 'droplets',
  oceanSound: 'drone',
  hear: 'Hear',
  nowHearing: 'What you are hearing',
  nothingPlaying: 'Turn sound on to hear the data. Each voice below is one real observation.',
  loudest: 'Loudest voices right now',
  left: 'left',
  right: 'right',
  centre: 'centre',
  rising: 'rising',
  falling: 'easing',
  steady: 'steady',
  vsYesterday: 'vs day before',
  pitch: 'pitch',
  rate: 'pulses/s',
  pan: 'position',
  hearChange: 'Hear the change',
  hearChangeHint: 'Louder and faster where values grew since the day before',
  play: 'Play',
  legend: 'Legend',
  loudness: 'Loudness',
  whatHearing: 'What am I hearing?',
  hearNeedle: 'The needle is the vertical line. It moves west to east, left to right, and you hear the column of the picture under it.',
  hearPitch: 'Height is pitch: the top of the picture is the highest note, the bottom the lowest. There are 12 bands.',
  hearLoud: 'Brightness is loudness: bright pixels are loud, dark pixels are silent.',
  hearColour: 'Colour is timbre: warm reds and oranges buzz, blues and greens stay soft.',
  hearScrub: 'Drag the needle slider, or click the picture, to hear any single spot. Drag across the picture to loop one part.',
  shareLink: 'Copy link',
  linkCopied: 'Link copied',
  story: 'Play the EIC story',
  storyStop: 'Stop the story',
  storyNext: 'Next',
  chooseAny: 'Choose any two',
  leftEar: 'Left ear',
  rightEar: 'Right ear',
  describeFrame: 'Describe this picture',
  scrub: 'Needle position',
  scrubHint: 'Drag, or use the arrow keys, to hear any part of the picture. Click or tap the picture to hear that spot.',
  loop: 'Loop',
  speed: 'Speed',
  loopStart: 'Loop starts here',
  loopEnd: 'Loop ends here',
  clearRegion: 'Whole picture',
  regionHint: 'Drag across the picture to loop just that part.',
  pause: 'Pause',
  prevDay: 'Previous day',
  nextDay: 'Next day',
  record: 'Record 30 s',
  recording: 'Recording… {s}s',
  recordSaved: 'Saved {name}',
  language: 'Language',
  reduceMotion: 'Reduce motion',
  highContrast: 'High contrast',
  narration: 'Spoken narration',
  spatial: 'Spatial audio',
  stereo: 'Stereo',
  hrtf: '3D (HRTF)',
  volume: 'Volume',
  shortcuts: 'Keyboard shortcuts',
  close: 'Close',
  realData: 'Real NASA data',
  sampleFallback: 'Offline sample (real snapshots could not load)',
  bdLens: 'Bangladesh',
  monsoonTitle: 'Bangladesh monsoon 2026',
  monsoonLead: 'Each division is a voice. West is left, east is right, north is higher. Heavier rain means denser, louder droplets.',
  compare2025: 'Compare with 2025',
  totalSince: 'Total since 1 June',
  ofNormal: 'of the 2001–2020 normal',
  wettest: 'Wettest day',
  pulseTitle: '146 years of global warming',
  pulseLead: 'One note per year. Higher pitch means a warmer planet compared with 1951–1980.',
  framesTitle: 'Earth Information Center frames',
  framesLead: 'A needle sweeps each NASA Earth Information Center frame or satellite image from west to east. Height is pitch, brightness is loudness, colour is timbre.',
  beforeAfter: 'Before / after',
  beforeAfterHint: 'Left ear plays the first image, right ear the second, at the same moment.',
  loadOwn: 'Load your own EIC image',
  eicGroup: 'NASA Earth Information Center (earth.gov)',
  imagery: 'NASA imagery',
  imageryHint: 'Show NASA satellite imagery of the selected day on the globe',
  dataFrom: 'Data from',
  listenHere: 'Listen here',
  noObs: 'No observation in the loaded data here.',
  skip: 'Skip to main content',
  // Navigation (v3)
  mainNav: 'Main',
  navExplore: 'Explore Earth',
  navJukebox: 'Data Jukebox',
  navAbout: 'About the Science',
  collections: 'Collections',
  menu: 'Menu',
  playingNow: 'Playing: {label}',
  pausePlayback: 'Pause {label}',
  // Landing
  heroKicker: 'NASA Space Apps Challenge 2026 · The Earth Information Jukebox · independent team entry, not an official NASA product',
  heroHeadline: 'Hear our changing planet',
  heroDataLine: 'Sonic Earth Atlas turns real NASA Earth data into sound you can explore. Each value becomes a pitch, a rhythm and a place in your headphones.',
  ctaExplore: 'Explore the globe',
  ctaStory: 'Listen to a data story',
  scrollHint: 'Scroll to see how it works',
  splitTitle: 'One planet, many measurements',
  splitBody: 'Satellites and models measure fire, rain, ocean heat, temperature, carbon dioxide and sea ice every day. We keep each value, its unit and its source, and play it with a published rule, so you can hear a pattern and then check it on the map.',
  splitPoint1: 'Real snapshots from NASA FIRMS, POWER, MUR SST, GISTEMP and GIBS, with dates',
  splitPoint2: 'One mapping rule per dataset, shown next to the sound',
  splitPoint3: 'Works by ear, keyboard and screen reader, in English and বাংলা',
  immersiveTitle: 'Turn it, then listen',
  immersiveBody: 'Drag the globe to turn it. Click any place to hear 45 years of its temperature and rain, or step through four days of fires, rain and ocean heat.',
  immersiveCta: 'Start exploring',
  howTitle: 'How data becomes sound',
  how1: 'NASA data',
  how1d: 'Real values from FIRMS, POWER, MUR, GISTEMP and GIBS',
  how2: 'Scale',
  how2d: 'Each value mapped to 0–1 with a published formula',
  how3: 'Synthesise',
  how3d: 'Sound generated live with Web Audio in your browser',
  how4: 'Hear and see',
  how4d: 'Place, value and sound explained side by side',
  globeStill: 'Earth from space. A still picture is shown because the 3D globe could not start on this device.',
  webglOff: 'The 3D globe could not start on this device, so the flat map is shown instead.',
  // Footer
  footerSonification: 'Every sound here is data sonification generated in your browser, not a recording.',
  footerNotNasa: 'Independent NASA Space Apps Challenge 2026 entry, not an official NASA product.',
  footerCredits: 'Data and imagery courtesy of NASA ESDIS, FIRMS, LaRC POWER, JPL PO.DAAC (via NOAA CoastWatch ERDDAP), GISS, GIBS and the Earth Information Center, plus NOAA GML and NSIDC.',
  footerSources: 'Sources',
  footerRepo: 'Source code on GitHub',
  // About the Science
  aboutTitle: 'About the science',
  aboutLead: 'How Sonic Earth Atlas turns measurements into sound, where every number comes from, and what it cannot tell you.',
  aboutHowTitle: 'How sonification works',
  aboutHowP1: 'Sonification means playing data as sound. Here each observation is first scaled to a number between 0 and 1 with a fixed formula. That number then sets one or more properties of a sound: pitch, loudness, rhythm, brightness or stereo position.',
  aboutHowP2: 'The rules are fixed per dataset, so the same data always gives the same sound. Longitude sets the stereo position (180°W is hard left, 180°E hard right). Nothing is pre-recorded: your browser builds every sound with Web Audio while you listen.',
  aboutMappingTitle: 'Mapping tables',
  aboutMappingLead: 'The three Atlas layers, with the exact formulas the app uses.',
  colLayer: 'Layer',
  colVariable: 'Variable and unit',
  colResolution: 'Resolution',
  colToNumber: 'Value to 0–1',
  colToSound: 'To sound',
  aboutTracksTitle: 'The other tracks',
  aboutTrackFrames: 'A needle sweeps each picture from west to east. Height in the picture is pitch (12 pentatonic bands), brightness is loudness and colour is timbre. This sonifies the picture, not calibrated values.',
  aboutTrackMonsoon: 'Each of the 8 divisions is a voice. West is left, east is right, north is higher. More daily rain gives denser and louder droplets.',
  aboutTrackPulse: 'One note per year. Higher pitch means a warmer year, more CO₂ or more sea ice. All three can play together as one chord.',
  aboutSourcesTitle: 'Data sources',
  srcFirms: 'Active fire detections, VIIRS 375 m, snapshot 2–7 Oct 2026',
  srcPower: 'Daily and monthly precipitation and temperature (MERRA-2 based), 1981–2025 and 2026 snapshots',
  srcMur: 'Monthly sea surface temperature anomaly, September 2026',
  srcGistemp: 'Global annual temperature anomaly, 1880–2025, vs 1951–1980',
  srcGml: 'Mauna Loa annual CO₂, 1959–2025',
  srcNsidc: 'Arctic September sea ice extent, 1979–2026',
  srcGibs: 'Daily satellite imagery requested live (true colour, thermal anomalies, rain rate and more)',
  srcEic: 'Earth Information Center frames, bundled with credit',
  aboutLimitsTitle: 'Limitations',
  limit1: 'The Atlas layers are snapshots of a few days, not a live feed. Dates are shown with every layer.',
  limit2: 'Rain points are a sample of the wettest grid points, not a full rain map.',
  limit3: 'NASA POWER values are model estimates for cells of about 50 km, not rain-gauge or station readings.',
  limit4: 'Fire values are grouped into 2° cells and keep only the strongest detection in each cell.',
  limit5: 'Picture sonification reads pixel colour and brightness, so it is only as accurate as the picture.',
  limit6: 'Sound supports the visuals; it does not replace the numbers, which are always shown as text too.',
  aboutA11yTitle: 'Accessibility controls',
  a11y1: 'Keyboard: S sound, Space play, ← → day, 1 2 3 layers, G M L views, T tour, ? settings.',
  a11y2: 'List view reads every observation as text, with its place, value and sound.',
  a11y3: 'Settings: বাংলা or English, reduced motion, high contrast, spoken narration, stereo or 3D audio, volume.',
  a11y4: 'If the 3D globe cannot start, a flat map or a still picture is shown and everything else keeps working.',
  aboutCreditsTitle: 'Credits',
  aboutCredits: 'Built by an independent team for the NASA Space Apps Challenge 2026. Globe textures from the three.js examples. Country shapes from Natural Earth via world-atlas. Fonts: Bricolage Grotesque, IBM Plex Sans and Noto Sans Bengali.',
  fullMethod: 'Full data and method notes',
  readAbout: 'Read About the Science',
};

export type StringKey = keyof typeof en;

const bn: Partial<Record<StringKey, string>> = {
  appName: 'সনিক আর্থ অ্যাটলাস',
  tagline: 'পৃথিবীর তথ্যের জুকবক্স',
  heroLead: 'নাসার আসল পৃথিবী পর্যবেক্ষণ আর স্যাটেলাইট ছবি, শব্দ হয়ে বাজে। একটা ট্র্যাক বেছে নিন, হেডফোন পরুন, শুনুন কোথায় আগুন জ্বলছে, বৃষ্টি হচ্ছে, সমুদ্র গরম হচ্ছে।',
  heroNote: 'প্রতিটি শব্দ ডেটা থেকে সরাসরি তৈরি হয়। কিছুই আগে থেকে রেকর্ড করা নয়।',
  heroHeadphones: 'হেডফোন ভালো: বাম-ডান শব্দ দ্রাঘিমাংশ অনুসরণ করে।',
  pickTrack: 'একটা ট্র্যাক বাছুন',
  startTour: '৪০ সেকেন্ডের ট্যুর চালান',
  listenNow: 'এখনই শুনুন',
  audioBlocked: 'আপনার ব্রাউজার শব্দ আটকে দিয়েছে। আবার চালান চাপুন, ভলিউম দেখুন আর সাইলেন্ট মোড বন্ধ করুন।',
  tryEic: 'এর বদলে সাথে থাকা একটি আর্থ ইনফরমেশন সেন্টার ফ্রেম চালান',
  exploreSilently: 'শব্দ ছাড়া দেখুন',
  track1: 'এই সপ্তাহের পৃথিবী',
  track1Desc: '২–৫ অক্টোবর ২০২৬-এর আগুন, বৃষ্টি আর সমুদ্রের তাপ, আপনার চারপাশে স্টেরিওতে।',
  track2: 'EIC ফ্রেম ও নাসার ছবি',
  track2Desc: 'নাসার আর্থ ইনফরমেশন সেন্টারের ছবি ও একই দিনের স্যাটেলাইট ছবি, বাম থেকে ডানে স্ক্যান হয়ে শব্দ হয়।',
  track3: 'বাংলাদেশের বর্ষা',
  track3Desc: '৮ বিভাগের দৈনিক বৃষ্টি, জুন–অক্টোবর ২০২৬, ২০২৫ আর ২০ বছরের গড়ের সাথে।',
  track4: 'পৃথিবীর প্রাণচিহ্ন',
  track4Desc: '১৮৮০ থেকে বৈশ্বিক তাপমাত্রা, ১৯৫৯ থেকে CO₂, ১৯৭৯ থেকে আর্কটিক বরফ, প্রতি বছর একটি সুর, আলাদা বা একসাথে। নিজের CSV-ও বাজাতে পারেন।',
  anyPlace: 'যেকোনো জায়গা',
  tracks: 'ট্র্যাক',
  globe: 'গ্লোব',
  map: 'মানচিত্র',
  list: 'তালিকা',
  soundOn: 'শব্দ চালু',
  soundOff: 'শব্দ বন্ধ',
  tour: 'ট্যুর',
  data: 'ডেটা ও পদ্ধতি',
  settings: 'সেটিংস',
  home: 'হোম',
  layers: 'স্তর',
  fire: 'দাবানল',
  rain: 'বৃষ্টি',
  ocean: 'সমুদ্রের তাপ',
  fireUnit: 'আগুনের শক্তি, মেগাওয়াট',
  rainUnit: 'দৈনিক বৃষ্টি, মিমি',
  oceanUnit: 'তাপমাত্রার বিচ্যুতি, °সে',
  fireSound: 'চটচট শব্দ',
  rainSound: 'ফোঁটা',
  oceanSound: 'গুঞ্জন',
  hear: 'শুনুন',
  nowHearing: 'আপনি কী শুনছেন',
  nothingPlaying: 'ডেটা শুনতে শব্দ চালু করুন। নিচের প্রতিটি কণ্ঠ একটি আসল পর্যবেক্ষণ।',
  loudest: 'এখন সবচেয়ে জোরালো',
  left: 'বামে',
  right: 'ডানে',
  centre: 'মাঝে',
  rising: 'বাড়ছে',
  falling: 'কমছে',
  steady: 'স্থির',
  vsYesterday: 'আগের দিনের তুলনায়',
  pitch: 'সুর',
  rate: 'স্পন্দন/সে',
  pan: 'অবস্থান',
  hearChange: 'পরিবর্তন শুনুন',
  hearChangeHint: 'আগের দিনের চেয়ে যেখানে বেড়েছে সেখানে শব্দ জোরালো ও দ্রুত',
  play: 'চালান',
  legend: 'নির্দেশিকা',
  loudness: 'জোর',
  whatHearing: 'আমি কী শুনছি?',
  hearNeedle: 'সুই হলো খাড়া দাগ। এটি পশ্চিম থেকে পূর্বে, বাম থেকে ডানে যায়, আর তার নিচের ছবির অংশের শব্দ শোনা যায়।',
  hearPitch: 'উচ্চতা মানে সুর: ছবির উপরের অংশে সবচেয়ে চড়া সুর, নিচে সবচেয়ে খাদ। মোট ১২টি স্তর।',
  hearLoud: 'উজ্জ্বলতা মানে জোর: উজ্জ্বল পিক্সেল জোরে, গাঢ় পিক্সেল নীরব।',
  hearColour: 'রং মানে ধ্বনির ধরন: লাল-কমলা ঝাঁঝালো, নীল-সবুজ নরম।',
  hearScrub: 'সুইয়ের স্লাইডার টানুন বা ছবিতে ক্লিক করুন, যেকোনো একটি জায়গার শব্দ শুনতে। ছবির উপর টেনে একটি অংশ বারবার শুনুন।',
  shareLink: 'লিংক কপি',
  linkCopied: 'লিংক কপি হয়েছে',
  story: 'EIC গল্প চালান',
  storyStop: 'গল্প থামান',
  storyNext: 'পরেরটি',
  chooseAny: 'যেকোনো দুটি বেছে নিন',
  leftEar: 'বাম কান',
  rightEar: 'ডান কান',
  describeFrame: 'ছবিটির বর্ণনা',
  scrub: 'সুইয়ের অবস্থান',
  scrubHint: 'টেনে বা অ্যারো কী দিয়ে ছবির যেকোনো অংশ শুনুন। ছবিতে ক্লিক বা ট্যাপ করলে সেই জায়গার শব্দ শোনা যাবে।',
  loop: 'বারবার',
  speed: 'গতি',
  loopStart: 'এখান থেকে শুরু',
  loopEnd: 'এখানে শেষ',
  clearRegion: 'পুরো ছবি',
  regionHint: 'ছবির উপর টেনে শুধু সেই অংশ বারবার শুনুন।',
  pause: 'থামান',
  prevDay: 'আগের দিন',
  nextDay: 'পরের দিন',
  record: '৩০ সেকেন্ড রেকর্ড',
  recording: 'রেকর্ড হচ্ছে… {s} সে',
  recordSaved: '{name} সংরক্ষিত',
  language: 'ভাষা',
  reduceMotion: 'কম অ্যানিমেশন',
  highContrast: 'উচ্চ কনট্রাস্ট',
  narration: 'কণ্ঠে বর্ণনা',
  spatial: 'স্থানিক শব্দ',
  stereo: 'স্টেরিও',
  hrtf: '৩ডি (HRTF)',
  volume: 'ভলিউম',
  shortcuts: 'কিবোর্ড শর্টকাট',
  close: 'বন্ধ',
  realData: 'নাসার আসল ডেটা',
  bdLens: 'বাংলাদেশ',
  monsoonTitle: 'বাংলাদেশের বর্ষা ২০২৬',
  monsoonLead: 'প্রতিটি বিভাগ একটি কণ্ঠ। পশ্চিম বামে, পূর্ব ডানে, উত্তর উঁচু সুরে। বেশি বৃষ্টি মানে ঘন ও জোরালো ফোঁটা।',
  compare2025: '২০২৫-এর সাথে তুলনা',
  totalSince: '১ জুন থেকে মোট',
  ofNormal: '২০০১–২০২০ গড়ের',
  wettest: 'সবচেয়ে ভেজা দিন',
  pulseTitle: '১৪৬ বছরের বৈশ্বিক উষ্ণায়ন',
  pulseLead: 'প্রতি বছর একটি সুর। ১৯৫১–১৯৮০-র তুলনায় পৃথিবী যত গরম, সুর তত উঁচু।',
  framesTitle: 'আর্থ ইনফরমেশন সেন্টারের ফ্রেম',
  framesLead: 'একটি সুই নাসার স্যাটেলাইট ছবি পশ্চিম থেকে পূর্বে স্ক্যান করে। উচ্চতা = সুর, উজ্জ্বলতা = জোর, রং = ধ্বনির ধরন।',
  beforeAfter: 'আগে / পরে',
  beforeAfterHint: 'বাম কানে প্রথম ছবি, ডান কানে দ্বিতীয় ছবি, একই সময়ে।',
  loadOwn: 'নিজের EIC ছবি দিন',
  eicGroup: 'নাসা আর্থ ইনফরমেশন সেন্টার (earth.gov)',
  imagery: 'নাসার ছবি',
  imageryHint: 'নির্বাচিত দিনের নাসার স্যাটেলাইট ছবি গ্লোবে দেখান',
  dataFrom: 'ডেটার উৎস',
  listenHere: 'এখানে শুনুন',
  noObs: 'এখানে লোড করা ডেটায় কোনো পর্যবেক্ষণ নেই।',
  skip: 'মূল অংশে যান',
  mainNav: 'প্রধান',
  navExplore: 'পৃথিবী ঘুরে দেখুন',
  navJukebox: 'ডেটা জুকবক্স',
  navAbout: 'বিজ্ঞানের কথা',
  collections: 'সংগ্রহ',
  menu: 'মেনু',
  playingNow: 'বাজছে: {label}',
  pausePlayback: '{label} থামান',
  heroKicker: 'নাসা স্পেস অ্যাপস চ্যালেঞ্জ ২০২৬ · আর্থ ইনফরমেশন জুকবক্স · স্বাধীন দলের প্রকল্প, নাসার অফিসিয়াল পণ্য নয়',
  heroHeadline: 'বদলে যাওয়া পৃথিবীকে শুনুন',
  heroDataLine: 'সনিক আর্থ অ্যাটলাস নাসার আসল পৃথিবী-ডেটাকে শব্দে রূপ দেয়, যা আপনি ঘুরে ঘুরে শুনতে পারেন। প্রতিটি মান হয়ে যায় একটি সুর, একটি ছন্দ আর হেডফোনে একটি অবস্থান।',
  ctaExplore: 'গ্লোব ঘুরে দেখুন',
  ctaStory: 'একটি ডেটা-গল্প শুনুন',
  scrollHint: 'কীভাবে কাজ করে দেখতে নিচে যান',
  splitTitle: 'এক পৃথিবী, অনেক পরিমাপ',
  splitBody: 'স্যাটেলাইট আর মডেল প্রতিদিন আগুন, বৃষ্টি, সমুদ্রের তাপ, তাপমাত্রা, কার্বন ডাই অক্সাইড আর সমুদ্র-বরফ মাপে। আমরা প্রতিটি মান, তার একক আর উৎস রেখে দিই এবং প্রকাশিত নিয়মে বাজাই, যাতে আপনি একটি ধরন শুনে মানচিত্রে মিলিয়ে দেখতে পারেন।',
  splitPoint1: 'নাসা FIRMS, POWER, MUR SST, GISTEMP ও GIBS-এর আসল স্ন্যাপশট, তারিখসহ',
  splitPoint2: 'প্রতিটি ডেটাসেটের একটি নিয়ম, শব্দের পাশেই দেখানো',
  splitPoint3: 'কান, কিবোর্ড ও স্ক্রিন রিডারে চলে, বাংলা ও ইংরেজিতে',
  immersiveTitle: 'ঘোরান, তারপর শুনুন',
  immersiveBody: 'গ্লোব টেনে ঘোরান। যেকোনো জায়গায় ক্লিক করে তার ৪৫ বছরের তাপমাত্রা আর বৃষ্টি শুনুন, অথবা চার দিনের আগুন, বৃষ্টি আর সমুদ্রের তাপ ধাপে ধাপে শুনুন।',
  immersiveCta: 'শুরু করুন',
  howTitle: 'ডেটা কীভাবে শব্দ হয়',
  how1: 'নাসার ডেটা',
  how1d: 'FIRMS, POWER, MUR, GISTEMP, GIBS থেকে আসল মান',
  how2: 'স্কেল',
  how2d: 'প্রতিটি মান ০ থেকে ১-এ, লেখা সূত্রে',
  how3: 'সংশ্লেষণ',
  how3d: 'ব্রাউজারে Web Audio দিয়ে সরাসরি শব্দ',
  how4: 'শুনুন ও দেখুন',
  how4d: 'অবস্থান, মান আর শব্দ একসাথে ব্যাখ্যা করা',
  globeStill: 'মহাকাশ থেকে পৃথিবী। এই ডিভাইসে ৩ডি গ্লোব চালু হয়নি, তাই একটি স্থির ছবি দেখানো হচ্ছে।',
  webglOff: 'এই ডিভাইসে ৩ডি গ্লোব চালু হয়নি, তাই সমতল মানচিত্র দেখানো হচ্ছে।',
  footerSonification: 'এখানের প্রতিটি শব্দ আপনার ব্রাউজারে ডেটা থেকে তৈরি (ডেটা সনিফিকেশন), কোনো রেকর্ডিং নয়।',
  footerNotNasa: 'নাসা স্পেস অ্যাপস চ্যালেঞ্জ ২০২৬-এর স্বাধীন প্রকল্প, নাসার অফিসিয়াল পণ্য নয়।',
  footerCredits: 'ডেটা ও ছবি: নাসা ESDIS, FIRMS, LaRC POWER, JPL PO.DAAC (NOAA CoastWatch ERDDAP হয়ে), GISS, GIBS ও আর্থ ইনফরমেশন সেন্টার, সাথে NOAA GML ও NSIDC।',
  footerSources: 'উৎস',
  footerRepo: 'GitHub-এ সোর্স কোড',
  aboutTitle: 'বিজ্ঞানের কথা',
  aboutLead: 'সনিক আর্থ অ্যাটলাস কীভাবে পরিমাপকে শব্দে রূপ দেয়, প্রতিটি সংখ্যা কোথা থেকে আসে, আর এটি কী বলতে পারে না।',
  aboutHowTitle: 'সনিফিকেশন কীভাবে কাজ করে',
  aboutHowP1: 'সনিফিকেশন মানে ডেটাকে শব্দ হিসেবে বাজানো। এখানে প্রতিটি পর্যবেক্ষণ প্রথমে একটি নির্দিষ্ট সূত্রে ০ থেকে ১-এর মধ্যে একটি সংখ্যায় আনা হয়। সেই সংখ্যা শব্দের এক বা একাধিক গুণ ঠিক করে: সুর, জোর, ছন্দ, উজ্জ্বলতা বা স্টেরিও অবস্থান।',
  aboutHowP2: 'প্রতিটি ডেটাসেটের নিয়ম স্থির, তাই একই ডেটা সবসময় একই শব্দ দেয়। দ্রাঘিমাংশ স্টেরিও অবস্থান ঠিক করে (১৮০° পশ্চিম একদম বামে, ১৮০° পূর্ব একদম ডানে)। কিছুই আগে থেকে রেকর্ড করা নয়: আপনি শোনার সময় ব্রাউজার Web Audio দিয়ে প্রতিটি শব্দ তৈরি করে।',
  aboutMappingTitle: 'ম্যাপিং টেবিল',
  aboutMappingLead: 'অ্যাটলাসের তিনটি স্তর, অ্যাপে ব্যবহৃত হুবহু সূত্রসহ।',
  colLayer: 'স্তর',
  colVariable: 'চলক ও একক',
  colResolution: 'রেজোলিউশন',
  colToNumber: 'মান থেকে ০–১',
  colToSound: 'শব্দে',
  aboutTracksTitle: 'অন্য ট্র্যাকগুলো',
  aboutTrackFrames: 'একটি সুই প্রতিটি ছবি পশ্চিম থেকে পূর্বে স্ক্যান করে। ছবির উচ্চতা = সুর (১২টি পেন্টাটনিক স্তর), উজ্জ্বলতা = জোর, রং = ধ্বনির ধরন। এটি ছবিকে বাজায়, মাপা মানকে নয়।',
  aboutTrackMonsoon: '৮টি বিভাগের প্রতিটি একটি কণ্ঠ। পশ্চিম বামে, পূর্ব ডানে, উত্তর উঁচু সুরে। দৈনিক বৃষ্টি বেশি হলে ফোঁটা ঘন ও জোরালো।',
  aboutTrackPulse: 'প্রতি বছর একটি সুর। উঁচু সুর মানে উষ্ণ বছর, বেশি CO₂ বা বেশি সমুদ্র-বরফ। তিনটি একসাথে একটি কর্ড হিসেবেও বাজতে পারে।',
  aboutSourcesTitle: 'ডেটার উৎস',
  srcFirms: 'সক্রিয় আগুন শনাক্তকরণ, VIIRS ৩৭৫ মি, স্ন্যাপশট ২–৭ অক্টোবর ২০২৬',
  srcPower: 'দৈনিক ও মাসিক বৃষ্টি ও তাপমাত্রা (MERRA-2 ভিত্তিক), ১৯৮১–২০২৫ ও ২০২৬-এর স্ন্যাপশট',
  srcMur: 'মাসিক সমুদ্রপৃষ্ঠের তাপমাত্রার বিচ্যুতি, সেপ্টেম্বর ২০২৬',
  srcGistemp: 'বৈশ্বিক বার্ষিক তাপমাত্রার বিচ্যুতি, ১৮৮০–২০২৫, ১৯৫১–১৯৮০-র তুলনায়',
  srcGml: 'মাউনা লোয়ার বার্ষিক CO₂, ১৯৫৯–২০২৫',
  srcNsidc: 'সেপ্টেম্বরে আর্কটিক সমুদ্র-বরফের বিস্তার, ১৯৭৯–২০২৬',
  srcGibs: 'সরাসরি আনা দৈনিক স্যাটেলাইট ছবি (প্রকৃত রং, তাপীয় বিচ্যুতি, বৃষ্টির হার ইত্যাদি)',
  srcEic: 'আর্থ ইনফরমেশন সেন্টারের ফ্রেম, কৃতজ্ঞতাসহ সাথে দেওয়া',
  aboutLimitsTitle: 'সীমাবদ্ধতা',
  limit1: 'অ্যাটলাসের স্তরগুলো কয়েক দিনের স্ন্যাপশট, সরাসরি ফিড নয়। প্রতিটি স্তরের সাথে তারিখ দেখানো হয়।',
  limit2: 'বৃষ্টির বিন্দুগুলো সবচেয়ে ভেজা গ্রিড-বিন্দুর নমুনা, পূর্ণ বৃষ্টির মানচিত্র নয়।',
  limit3: 'নাসা POWER-এর মান প্রায় ৫০ কিমি ঘরের মডেল-অনুমান, বৃষ্টিমাপক বা স্টেশনের পাঠ নয়।',
  limit4: 'আগুনের মান ২° ঘরে ভাগ করা, প্রতিটি ঘরে শুধু সবচেয়ে শক্তিশালী শনাক্তকরণ রাখা হয়।',
  limit5: 'ছবির সনিফিকেশন পিক্সেলের রং ও উজ্জ্বলতা পড়ে, তাই এটি ছবির মতোই নির্ভুল।',
  limit6: 'শব্দ ছবিকে সাহায্য করে, সংখ্যার বদলে নয়; সংখ্যা সবসময় লেখাতেও দেখানো হয়।',
  aboutA11yTitle: 'অ্যাক্সেসিবিলিটি নিয়ন্ত্রণ',
  a11y1: 'কিবোর্ড: S শব্দ, Space চালান, ← → দিন, 1 2 3 স্তর, G M L দৃশ্য, T ট্যুর, ? সেটিংস।',
  a11y2: 'তালিকা দৃশ্য প্রতিটি পর্যবেক্ষণ লেখায় পড়ে শোনায়, অবস্থান, মান ও শব্দসহ।',
  a11y3: 'সেটিংস: বাংলা বা ইংরেজি, কম অ্যানিমেশন, উচ্চ কনট্রাস্ট, কণ্ঠে বর্ণনা, স্টেরিও বা ৩ডি শব্দ, ভলিউম।',
  a11y4: '৩ডি গ্লোব চালু না হলে সমতল মানচিত্র বা স্থির ছবি দেখানো হয়, বাকি সব কাজ করে।',
  aboutCreditsTitle: 'কৃতজ্ঞতা',
  aboutCredits: 'নাসা স্পেস অ্যাপস চ্যালেঞ্জ ২০২৬-এর জন্য একটি স্বাধীন দলের তৈরি। গ্লোবের টেক্সচার three.js উদাহরণ থেকে। দেশের আকার Natural Earth (world-atlas) থেকে। ফন্ট: Bricolage Grotesque, IBM Plex Sans ও Noto Sans Bengali।',
  fullMethod: 'ডেটা ও পদ্ধতির পূর্ণ বিবরণ',
  readAbout: 'বিজ্ঞানের কথা পড়ুন',
};

export const STRINGS: Record<Lang, Partial<Record<StringKey, string>>> = { en, bn };
