export type Lang = 'en' | 'bn';

const en = {
  appName: 'Sonic Earth Atlas',
  tagline: 'An Earth Information Jukebox',
  heroLead: 'Real NASA Earth observations and NASA imagery, played as sound. Pick a track, put on headphones, and listen to where the planet is burning, raining and warming.',
  heroNote: 'Every sound is generated live from the data. Nothing is pre-recorded.',
  heroHeadphones: 'Headphones help: left and right follow longitude.',
  pickTrack: 'Pick a track',
  listenNow: 'Listen now',
  audioBlocked: 'Your browser blocked the sound. Press Play again, check the volume, and turn off silent mode.',
  tryEic: 'Play a bundled Earth Information Center frame instead',
  startTour: 'Play the 40-second tour',
  exploreSilently: 'Explore without sound',
  track1: 'Planet this week',
  track1Desc: 'Fires, rain and ocean heat from 2–5 October 2026, placed around you in stereo.',
  track2: 'EIC frames + NASA imagery',
  track2Desc: 'NASA Earth Information Center visuals and satellite images of the same days, swept left to right and turned into sound.',
  track3: 'Bangladesh monsoon',
  track3Desc: 'Daily rain in 8 divisions, June to October 2026, against 2025 and the 20-year normal.',
  track4: "Earth's vital signs",
  track4Desc: 'Global temperature since 1880, CO₂ since 1959 and Arctic sea ice since 1979, one note per year, alone or as one chord. Or play your own CSV.',
  anyPlace: 'Any place',
  tracks: 'Tracks',
  globe: 'Globe',
  map: 'Map',
  list: 'List',
  soundOn: 'Sound on',
  soundOff: 'Sound off',
  tour: 'Tour',
  data: 'Data & method',
  settings: 'Settings',
  home: 'Home',
  layers: 'Layers',
  fire: 'Wildfires',
  rain: 'Rain',
  ocean: 'Ocean heat',
  fireUnit: 'fire power, MW',
  rainUnit: 'daily rain, mm',
  oceanUnit: 'SST anomaly, °C',
  fireSound: 'crackle',
  rainSound: 'droplets',
  oceanSound: 'drone',
  hear: 'Hear',
  nowHearing: 'What you are hearing',
  nothingPlaying: 'Turn sound on to hear the data. Each voice below is one real observation.',
  loudest: 'Loudest voices right now',
  left: 'left',
  right: 'right',
  centre: 'centre',
  rising: 'rising',
  falling: 'easing',
  steady: 'steady',
  vsYesterday: 'vs day before',
  pitch: 'pitch',
  rate: 'pulses/s',
  pan: 'position',
  hearChange: 'Hear the change',
  hearChangeHint: 'Louder and faster where values grew since the day before',
  play: 'Play',
  legend: 'Legend',
  loudness: 'Loudness',
  whatHearing: 'What am I hearing?',
  hearNeedle: 'The needle is the vertical line. It moves west to east, left to right, and you hear the column of the picture under it.',
  hearPitch: 'Height is pitch: the top of the picture is the highest note, the bottom the lowest. There are 12 bands.',
  hearLoud: 'Brightness is loudness: bright pixels are loud, dark pixels are silent.',
  hearColour: 'Colour is timbre: warm reds and oranges buzz, blues and greens stay soft.',
  hearScrub: 'Drag the needle slider, or click the picture, to hear any single spot. Drag across the picture to loop one part.',
  shareLink: 'Copy link',
  linkCopied: 'Link copied',
  story: 'Play the EIC story',
  storyStop: 'Stop the story',
  storyNext: 'Next',
  chooseAny: 'Choose any two',
  leftEar: 'Left ear',
  rightEar: 'Right ear',
  describeFrame: 'Describe this picture',
  scrub: 'Needle position',
  scrubHint: 'Drag, or use the arrow keys, to hear any part of the picture. Click or tap the picture to hear that spot.',
  loop: 'Loop',
  speed: 'Speed',
  loopStart: 'Loop starts here',
  loopEnd: 'Loop ends here',
  clearRegion: 'Whole picture',
  regionHint: 'Drag across the picture to loop just that part.',
  pause: 'Pause',
  prevDay: 'Previous day',
  nextDay: 'Next day',
  record: 'Record 30 s',
  recording: 'Recording… {s}s',
  recordSaved: 'Saved {name}',
  language: 'Language',
  reduceMotion: 'Reduce motion',
  highContrast: 'High contrast',
  narration: 'Spoken narration',
  calmBackground: 'Pause background motion',
  calmBackgroundNote: 'Stops the starfield, the idle globe spin and drifting clouds. Fly-to, playback and the rest keep working.',
  diagnostics: 'Performance diagnostics',
  srNote: 'Screen readers: every view has headings and live descriptions. The List view reads each observation as a table row; press Enter on a row to hear it. In the Data Jukebox, the “What you hear” legend explains each sound in text.',
  spatial: 'Spatial audio',
  stereo: 'Stereo',
  hrtf: '3D (HRTF)',
  volume: 'Volume',
  shortcuts: 'Keyboard shortcuts',
  close: 'Close',
  realData: 'Real NASA data',
  sampleFallback: 'Offline sample (real snapshots could not load)',
  bdLens: 'Bangladesh',
  monsoonTitle: 'Bangladesh monsoon 2026',
  monsoonLead: 'Each division is a voice. West is left, east is right, north is higher. Heavier rain means denser, louder droplets.',
  compare2025: 'Compare with 2025',
  totalSince: 'Total since 1 June',
  ofNormal: 'of the 2001–2020 normal',
  wettest: 'Wettest day',
  pulseTitle: '146 years of global warming',
  pulseLead: 'One note per year. Higher pitch means a warmer planet compared with 1951–1980.',
  framesTitle: 'Earth Information Center frames',
  framesLead: 'A needle sweeps each NASA Earth Information Center frame or satellite image from west to east. Height is pitch, brightness is loudness, colour is timbre.',
  beforeAfter: 'Before / after',
  beforeAfterHint: 'Left ear plays the first image, right ear the second, at the same moment.',
  loadOwn: 'Load your own EIC image',
  eicGroup: 'NASA Earth Information Center (earth.gov)',
  imagery: 'NASA imagery',
  imageryHint: 'Show NASA satellite imagery of the selected day on the globe',
  dataFrom: 'Data from',
  listenHere: 'Listen here',
  noObs: 'No observation in the loaded data here.',
  skip: 'Skip to main content',
  // Navigation (v3)
  mainNav: 'Main',
  navExplore: 'Explore Earth',
  loadingGlobe: 'Loading globe…',
  loadingView: 'Loading…',
  viewGroup: 'View',
  navJukebox: 'Data Jukebox',
  navAbout: 'About the Science',
  collections: 'Collections',
  menu: 'Menu',
  playingNow: 'Playing: {label}',
  pausePlayback: 'Pause {label}',
  // Landing
  heroKicker: 'NASA Space Apps Challenge 2026 · The Earth Information Jukebox · independent team entry, not an official NASA product',
  heroHeadline: 'Hear our changing planet',
  heroDataLine: 'Sonic Earth Atlas turns real NASA Earth data into sound you can explore. Each value becomes a pitch, a rhythm and a place in your headphones.',
  ctaExplore: 'Explore the globe',
  ctaStory: 'Listen to a data story',
  scrollHint: 'Scroll to see how it works',
  splitTitle: 'One planet, many measurements',
  splitBody: 'Satellites and models measure fire, rain, ocean heat, temperature, carbon dioxide and sea ice every day. We keep each value, its unit and its source, and play it with a published rule, so you can hear a pattern and then check it on the map.',
  splitPoint1: 'Real snapshots from NASA FIRMS, POWER, MUR SST, GISTEMP and GIBS, with dates',
  splitPoint2: 'One mapping rule per dataset, shown next to the sound',
  splitPoint3: 'Works by ear, keyboard and screen reader, in English and বাংলা',
  immersiveTitle: 'Turn it, then listen',
  immersiveBody: 'Drag the globe to turn it. Click any place to hear 45 years of its temperature and rain, or step through four days of fires, rain and ocean heat.',
  immersiveCta: 'Start exploring',
  // Landing carousel (Phase 9)
  carouselLabel: 'Choose a view of Earth',
  carouselOf: '{n} of {total}: {name}',
  ctaStart: 'Get started',
  ctaLearn: 'Learn more',
  ctaPreview: 'Play a short preview',
  ctaStopPreview: 'Stop preview',
  ctaOpenTrack: 'Open this track',
  ctaBackLevel: 'Back',
  carPrev: 'Previous Earth: {name}',
  carNext: 'Next Earth: {name}',
  carGoTo: 'Show {name}',
  carHowItWorks: 'See how it works',
  previewNote: 'The preview is a short melody made from the values on this card: higher value, higher pitch.',
  levelOverview: 'Overview',
  levelDetail: 'Detail',
  levelImmersive: 'Immersive view',
  mFires: 'fire detections on {date}',
  mStrongest: 'strongest fire ({unit})',
  mFrames: 'Earth Information Center pictures to play',
  mCities: 'cities in Bangladesh',
  mSylhet: 'mm of rain in Sylhet, {from} to {to}',
  mAnomaly: '°C in {year}, against the 1951–1980 average',
  mYears: 'years of records since 1880',
  metricsLabel: 'Key numbers',
  planetCredit: 'Planet: NASA Blue Marble imagery on a 3D globe.',
  w1Kicker: 'A1 · Planet this week',
  w1Name: 'Fire',
  w1Line: 'Where the planet burned, 2–5 October 2026, placed around you in stereo.',
  w1Title: 'The burning planet',
  w1Body: 'NASA FIRMS satellites detect active fires several times a day. Each fire becomes a note: a hotter fire sounds higher, and its longitude puts it left or right in your headphones. This is a snapshot of four days, 2–5 October 2026.',
  w1Deep: 'Every dot is a heat anomaly seen by a satellite, not a confirmed wildfire: it can be a crop burn, a gas flare or a volcano. In the Atlas you can turn the globe, click a country and step through the four days to hear fires move.',
  w1Src: 'Data: NASA FIRMS active fires, snapshot 2–5 October 2026.',
  w1Pic: 'Picture: NASA GIBS VIIRS true colour, 3 October 2026.',
  w2Kicker: 'A2 · EIC frames and NASA imagery',
  w2Name: 'Imagery',
  w2Line: 'Satellite pictures played as sound, one sweep at a time.',
  w2Title: 'The planet seen from space',
  w2Body: 'Earth Information Center maps and NASA satellite pictures become sound by scanning the image: dark and bright areas change pitch and loudness, and the position across the picture sets left and right. Pick a frame and hear it sweep.',
  w2Deep: 'A picture is a table of numbers. We read its pixels along a path and play each one with a published rule, and we keep the colour legend, the date and the credit beside the sound. Parts with no data stay silent.',
  w2Src: 'Method: pixel sweep of Earth Information Center and NASA GIBS pictures (see About).',
  w2Pic: 'Picture: NASA GIBS VIIRS true colour, 3 October 2026.',
  w3Kicker: 'B1 · Bangladesh monsoon',
  w3Name: 'Monsoon',
  w3Line: 'A summer of rain in eight cities, against a normal year.',
  w3Title: 'The rainy planet',
  w3Body: 'Bangladesh gets most of its rain from June to September. We play the daily NASA POWER rainfall for eight cities beside their 2001–2020 average, so you can hear a wet day stand out from a normal one.',
  w3Deep: 'Daily precipitation from NASA POWER (MERRA-2 based), from 1 June 2026, compared with the 2001–2020 monthly mean. Heavier days sound louder and denser. This is modelled reanalysis data, not a rain-gauge reading.',
  w3Src: 'Data: NASA POWER daily precipitation and 2001–2020 climatology for eight cities.',
  w3Pic: 'Picture: NASA GEOS rain, Earth Information Center.',
  w4Kicker: 'B2 · Earth’s vital signs',
  w4Name: 'Warming',
  w4Line: 'More than a century of global temperature, in one rising line of sound.',
  w4Title: 'The warming planet',
  w4Body: 'NASA GISTEMP gives one number per year: how far the global temperature is from the 1951–1980 average. We play 1880 to the latest year as pitch, so cold years sit low and warm years high.',
  w4Deep: 'Each value is a land and ocean annual anomaly in °C against the 1951–1980 baseline, so each note is one full year. Blue years are below the baseline and pink years above it. Open the track to compare it with other series.',
  w4Src: 'Data: NASA GISS GISTEMP v4, annual land and ocean anomaly.',
  w4Pic: 'Picture: ocean heat content, Earth Information Center.',
  howTitle: 'How data becomes sound',
  how1: 'NASA data',
  how1d: 'Real values from FIRMS, POWER, MUR, GISTEMP and GIBS',
  how2: 'Scale',
  how2d: 'Each value mapped to 0–1 with a published formula',
  how3: 'Synthesise',
  how3d: 'Sound generated live with Web Audio in your browser',
  how4: 'Hear and see',
  how4d: 'Place, value and sound explained side by side',
  globeStill: 'Earth from space. A still picture is shown because the 3D globe could not start on this device.',
  webglOff: 'The 3D globe could not start on this device, so the flat map is shown instead.',
  // Footer
  footerSonification: 'Every sound here is data sonification generated in your browser, not a recording.',
  footerNotNasa: 'Independent NASA Space Apps Challenge 2026 entry, not an official NASA product.',
  footerCredits: 'Data and imagery courtesy of NASA ESDIS, FIRMS, LaRC POWER, JPL PO.DAAC (via NOAA CoastWatch ERDDAP), GISS, GIBS and the Earth Information Center, plus NOAA GML and NSIDC.',
  footerSources: 'Sources',
  footerRepo: 'Source code on GitHub',
  // About the Science
  aboutTitle: 'About the science',
  aboutLead: 'How Sonic Earth Atlas turns measurements into sound, where every number comes from, and what it cannot tell you.',
  aboutHowTitle: 'How sonification works',
  aboutHowP1: 'Sonification means playing data as sound. Here each observation is first scaled to a number between 0 and 1 with a fixed formula. That number then sets one or more properties of a sound: pitch, loudness, rhythm, brightness or stereo position.',
  aboutHowP2: 'The rules are fixed per dataset, so the same data always gives the same sound. Longitude sets the stereo position (180°W is hard left, 180°E hard right). Nothing is pre-recorded: your browser builds every sound with Web Audio while you listen.',
  aboutMappingTitle: 'Mapping tables',
  aboutMappingLead: 'The three Atlas layers, with the exact formulas the app uses.',
  aboutSeriesTitle: 'Data Jukebox series',
  aboutSeriesLead: 'Each series is placed in a fixed range, the same for every period and country, and played on a G-major pentatonic scale from G3 (196 Hz) to G5 (784 Hz). A bigger change from the previous value gives more pulses (1–6). A missing value is silence.',
  colSeries: 'Series',
  colRange: 'Fixed range',
  colBaseline: 'Baseline',
  aboutSqrt: 'square-root scale',
  colLayer: 'Layer',
  colVariable: 'Variable and unit',
  colResolution: 'Resolution',
  colToNumber: 'Value to 0–1',
  colToSound: 'To sound',
  aboutTracksTitle: 'The other tracks',
  aboutTrackFrames: 'A needle sweeps each picture from west to east. Height in the picture is pitch (12 pentatonic bands), brightness is loudness and colour is timbre. This sonifies the picture, not calibrated values.',
  aboutTrackMonsoon: 'Each of the 8 divisions is a voice. West is left, east is right, north is higher. More daily rain gives denser and louder droplets.',
  aboutTrackPulse: 'One note per year. Higher pitch means a warmer year, more CO₂ or more sea ice. All three can play together as one chord.',
  aboutSourcesTitle: 'Data sources',
  srcFirms: 'Active fire detections, VIIRS 375 m, snapshot 2–7 Oct 2026',
  srcPower: 'Daily and monthly precipitation and temperature (MERRA-2 based), 1981–2025 and 2026 snapshots',
  srcMur: 'Monthly sea surface temperature anomaly, September 2026',
  srcGistemp: 'Global annual temperature anomaly, 1880–2025, vs 1951–1980',
  srcGml: 'Mauna Loa annual CO₂, 1959–2025',
  srcNsidc: 'Arctic September sea ice extent, 1979–2026',
  srcGibs: 'Daily satellite imagery requested live (true colour, thermal anomalies, rain rate and more)',
  srcEic: 'Earth Information Center frames, bundled with credit',
  aboutLimitsTitle: 'Limitations',
  limit1: 'The Atlas layers are snapshots of a few days, not a live feed. Dates are shown with every layer.',
  limit2: 'Rain points are a sample of the wettest grid points, not a full rain map.',
  limit3: 'NASA POWER values are model estimates for cells of about 50 km, not rain-gauge or station readings.',
  limit4: 'Fire values are grouped into 2° cells and keep only the strongest detection in each cell.',
  limit5: 'Picture sonification reads pixel colour and brightness, so it is only as accurate as the picture.',
  limit6: 'Sound supports the visuals; it does not replace the numbers, which are always shown as text too.',
  aboutA11yTitle: 'Accessibility controls',
  a11y1: 'Keyboard: S sound, Space play, ← → day, 1 2 3 layers, G M L views, T tour, ? settings.',
  a11y2: 'List view reads every observation as text, with its place, value and sound.',
  a11y3: 'Settings: বাংলা or English, reduced motion, high contrast, spoken narration, stereo or 3D audio, volume.',
  a11y4: 'If the 3D globe cannot start, a flat map or a still picture is shown and everything else keeps working.',
  aboutCreditsTitle: 'Credits',
  aboutCredits: 'Built by an independent team for the NASA Space Apps Challenge 2026. Globe textures from the three.js examples. Country shapes from Natural Earth via world-atlas. Fonts: Bricolage Grotesque, IBM Plex Sans and Noto Sans Bengali.',
  fullMethod: 'Full data and method notes',
  readAbout: 'Read About the Science',
  country: 'Country',
  countrySearch: 'Search for a country',
  countryPlaceholder: 'Type a country name…',
  countryResults: '{n} countries found',
  countryNone: 'No country matches “{q}”',
  countrySelected: 'Selected country',
  countryNoneSelected: 'No country selected. Search, or click the globe or map.',
  countryClear: 'Clear country',
  countryPoint: 'Representative point',
  countryPointNote: 'Centre of the largest land area, used for point data. Not an average of the whole country.',
  countryChosen: '{name} selected',
  countryCleared: 'Country cleared',
  countryHover: '{name}, click to select',
  countryOcean: 'Open ocean or no country here',
  countryUnderFocus: 'Country at the focus point',
  countrySelectKey: 'Press C to select it',
  resetView: 'Reset view',
  selectedBadge: 'Selected',
  provSource: 'Source',
  provVariable: 'Variable',
  provUnit: 'Unit',
  provPeriod: 'Period',
  provSpatial: 'Spatial resolution',
  provTemporal: 'Temporal resolution',
  provCredit: 'Credit',
  provSnapshot: 'Snapshot {date}',
  provSnapshotNoDate: 'Snapshot',
  provLive: 'Live',
  provContext: 'Global context',
  provSample: 'Sample',
  provMethod: 'Method and limits',
  provMethodHead: 'Method',
  provLimitsHead: 'Limits',
  provOpenSource: 'Open source page',
  dsLoading: 'Loading…',
  dsEmpty: 'Nothing to show here.',
  dsStale: 'This data may be out of date.',
  dsError: 'Could not load this data.',
  dsOffline: 'You appear to be offline.',
  dsRetry: 'Try again',
  profileSample: 'The offline sample is playing, so no real country figures are shown.',
  profileTitle: 'Science profile',
  profileHave: 'Data for this country',
  profileChecked: 'Checked, nothing inside the border',
  profileContext: 'Global context, not about this country',
  profileEmpty: 'No data from this app covers {name}. Nothing is shown rather than a stand-in.',
  profilePick: 'Choose a country to see which NASA data exists for it.',
  profileRange: 'Range',
  profileStamp: 'Latest source stamp',
  profileExplore: 'Explore its sound',
  profileExploreNote: 'Opens the Data Jukebox on this country\'s monthly temperature story.',
  profileCells: '{n} inside',
  profileMax: 'strongest {v} {u}',
  profileMean: 'mean of {n}: {v} {u}',
  profileDays: '{n} days with data',
  profileNoCells: '{what}: no cell or point inside the border',
  profileSparkTitle: 'Monthly climate at the representative point',
  profileSparkAlt: 'Annual mean temperature {a} to {b} °C, {from} to {to}',
  profilePointOnly: 'NASA POWER, one ~50 km cell at {pt}. Not an average of the country.',
  profileLoadingPower: 'Asking NASA POWER for monthly values…',
  profileTable: 'Table of values',
  profileNone: 'None',
  jbStoriesNav: 'Stories',
  jbLead: 'Pick a data story, move along its real observation dates, and read what each value means. Every number shows its source.',
  jbStories: 'Data stories',
  jbPrevStories: 'Scroll stories left',
  jbNextStories: 'Scroll stories right',
  jbNoStories: 'No story matches these filters. Press Reset to see them all.',
  jbNowShowing: 'Showing',
  jbPicture: 'Picture',
  jbShow: 'Show',
  jbFilters: 'Filters',
  jbTimeline: 'Timeline',
  jbStory: 'Story',
  jbReset: 'Reset',
  jbPeriod: 'Period',
  jbOnePeriod: 'This story has one period only ({y}).',
  jbNoPeriod: 'Choose a story with a time series to pick a period.',
  jbFrom: 'From',
  jbTo: 'To',
  jbFirstYear: 'First year',
  jbLastYear: 'Last year',
  jbTopic: 'Topic',
  jbAll: 'All',
  jbRegion: 'Region',
  jbSource: 'Source',
  jbAllSources: 'All sources',
  jbCountryNote: 'Country stories use one representative point (temperature, rain) and fire cells inside the border.',
  jbCountryHint: 'Choose a country to add its own stories.',
  jbCollectionsNote: 'The full players from before, unchanged.',
  jbTimelineAll: '{n} observations. ↑ ↓ move, Home and End jump.',
  jbTimelineBuckets: '{n} observations, grouped. → opens a group, ← closes it.',
  jbTimelineLabel: 'Observation dates: {what}',
  jbBucketCount: '{n} values',
  jbBucketGaps: '{n} missing',
  jbActive: 'current',
  jbGap: 'no data',
  jbGapsNote: '{n} missing values are drawn as breaks in the line, not filled in.',
  jbNoValues: 'This series has no valid values in the chosen period.',
  jbTime: 'Time',
  jbChartAlt: '{what}, {from} to {to}, from {lo} to {hi}.',
  jbCap: '{time}: {what} was {v}.',
  jbCapGap: '{time}: no value for {what}. The gap is left empty.',
  jbCapUp: 'Up {d} from {from}.',
  jbCapDown: 'Down {d} from {from}.',
  jbCapSame: 'Same as {from}.',
  jbPictureNoTimeline: 'This story is one picture, so it has no timeline. Open it in the frame player to hear it swept left to right.',
  jbSoundNote: 'The full player for this data is still there too.',
  jbOpenCollection: 'Hear it in {name}',
  jbPrev: 'Previous observation',
  jbNext: 'Next observation',
  jbPosition: '{i} of {n}',
  plSound: 'Sound',
  plPlay: 'Play',
  plPause: 'Pause',
  plResume: 'Resume',
  plStop: 'Stop',
  plSeek: 'Position in the series',
  plVolume: 'Volume',
  plMute: 'Mute',
  plSpeed: 'Speed',
  plTimeMode: 'Timing',
  plEven: 'Even steps',
  plProportional: 'Real-time spacing',
  plTimeNote: 'Even steps give every value the same length. Real-time spacing leaves silence where dates are far apart.',
  plCompare: 'Compare two periods',
  plCompareA: 'A is the period chosen in Filters: {p}.',
  plCompareB: 'Period B',
  plLayout: 'Layout',
  plSplit: 'A left ear, B right ear',
  plSequence: 'A, then B',
  plCompareNote: 'Both use the same mapping, so if B sounds higher, its values are higher.',
  plCompareNeedsYears: 'This story needs at least two years to compare periods.',
  plNote: 'Audio is data sonification, not a recording. It only starts when you press Play.',
  plState: 'Player: {s}',
  plState_idle: 'not loaded',
  plState_loading: 'loading data',
  plState_ready: 'ready',
  plState_playing: 'playing',
  plState_paused: 'paused',
  plState_ended: 'finished',
  plState_error: 'error',
  plNoSound: 'This story is one picture, so it has no series to play here.',
  lgTitle: 'What you hear',
  lgRange: 'Fixed range for this dataset: {lo} (lowest note, G3) to {hi} (highest note, G5).',
  lgRangeOwn: 'Range from this series itself: {lo} to {hi}.',
  lgNote: '{v} → {note} ({hz} Hz)',
  lgPitch: 'Pitch: {pct}% of the way up the fixed range.',
  lgClippedHigh: 'Above the range, so it plays the top note.',
  lgClippedLow: 'Below the range, so it plays the bottom note.',
  lgPulses: 'Pulses: {n} of 6, from a change of {d} since {from}.',
  lgPulsesFirst: 'Pulses: 1. Nothing earlier to compare with.',
  lgTimbreWarm: 'Timbre: warm triangle, at or above the {b} baseline.',
  lgTimbreSoft: 'Timbre: soft sine, below the {b} baseline.',
  lgTimbrePlain: 'Timbre: plain sine. This dataset has no baseline.',
  lgSilence: 'Silence: no value here, and the gap is not filled.',
  lgNoCursor: 'Pick a point on the timeline to read how it sounds.',
  lgLive: '{cap} Sound: {note}, {n} pulses.',
  topic_temperature: 'Temperature',
  topic_greenhouse: 'Greenhouse gases',
  topic_ice: 'Sea ice',
  topic_ocean: 'Ocean heat',
  topic_fire: 'Fire',
  topic_rain: 'Rain',
  topic_agriculture: 'Crops',
  region_global: 'Global',
  region_bangladesh: 'Bangladesh',
  region_country: 'Country',
  topicsTitle: 'Earth topics',
  topicsLead: 'Six ways into the data. Each one opens a real story in the Data Jukebox.',
  topicSkip: 'Skip animation',
  topicPrev: 'Previous topic',
  topicNext: 'Next topic',
  topicOf: 'Topic {i} of {n}: {name}',
  topicMore: 'Look closer',
  topicImmersive: 'Full view',
  topicBack: 'Back',
  topicListen: 'Open in the Jukebox',
  topicSparkAlt: 'Line of the real values: {what}',
  topicLine_temperature: 'The planet is about 1.3 °C warmer than in the late 1800s.',
  topicLine_greenhouse: 'CO₂ in the air has risen every year since measurements began.',
  topicLine_ocean: 'The ocean stores most of the extra heat.',
  topicLine_ice: 'Arctic summer ice now covers far less sea than in 1979.',
  topicLine_fire: 'Satellites see the strongest fires on Earth every day.',
  topicLine_rain: 'Monsoon rain arrives in bursts, not evenly.',
  topicDetail_temperature: 'NASA GISS combines thousands of land stations and ocean measurements into one yearly global value, as a difference from the 1951–1980 average.',
  topicDetail_greenhouse: 'The Mauna Loa record is the yearly mean of CO₂ measured in the air in Hawaii, the longest direct record. The picture is the Earth Information Center’s greenhouse gas index.',
  topicDetail_ocean: 'The Earth Information Center chart shows the heat added to the ocean since 1957, in zettajoules. It is a picture, so the Jukebox shows it with its source rather than as numbers.',
  topicDetail_ice: 'Each value is the September mean extent of Arctic sea ice from satellites, the smallest point of each year.',
  topicDetail_fire: 'VIIRS detects active fires at 375 m. The snapshot keeps the strongest 2° cells of each day; the story plays the strongest one.',
  topicDetail_rain: 'Daily rain from NASA POWER at the Sylhet division point, June to October 2026. The picture is a GEOS weather model view, not a photograph.',
  inspTitle: 'Place details',
  inspMeasured: 'Measured value',
  inspVsPrev: 'vs previous day',
  inspIntensity: 'Sound intensity (0 to 1)',
  inspCoords: 'Coordinates',
  inspPan: 'Stereo pan',
  inspLeft: '{n}% left',
  inspRight: '{n}% right',
  inspCentre: 'centre',
  inspTime: 'Timestamp',
  inspConf: 'Detection confidence',
  inspHow: 'How this value becomes sound',
  inspSource: 'Source: {p}',
  inspPlay: 'Play this place',
  inspLat: 'lat',
  inspLon: 'lon',
  dataTitle: 'Data and method',
  spin: 'Spin',
  spinHint: 'Spin the globe',
  panels: 'Panels',
  imgUnavailable: 'Image unavailable offline',
  frHigh: '▲ high',
  frLow: '▼ low',
  frHighNote: 'top of the picture = high pitch',
  frLowNote: 'bottom = low pitch',
  frBright: 'brighter = louder',
  frWarm: 'warm = buzzy',
  frCool: 'cool = soft',
  frOne: 'One image',
  frMode: 'Mode',
  stop: 'Stop',
  year: 'Year',
  unitMm: 'mm',
  bdLoadFail: 'Bangladesh data could not be loaded.',
  bdMapLabel: 'Map of Bangladesh with 8 divisional cities. On {date} the wettest is {city}.',
  bdCityLabel: '{city}: {mm} mm',
  bdCircle: 'Circle size = rain that day. Click a city to see its season.',
  bdRainTitle: '{city}: daily rain, {year}',
  bdChartUnit: 'mm/day · NASA POWER',
  bdChartLabel: 'Daily rain in {city}, {year}. Wettest day {mm} millimetres.',
  bdDashed: 'Dashed line: average daily rain for that month, 2001–2020 (NASA POWER climatology).',
  bdTotalLine: '{total} ({from}–{to} {year}). {city}: {mm} mm, {wettest} {day} ({max} mm).',
  bdCredit: 'Source: {src}. Values are model-based estimates for the city location (about 50 km cells), not rain-gauge readings.',
  bdYear: '{year}: {mm} mm',
  dmIntro: 'Everything you hear comes from public NASA sources (plus the NOAA CO₂ and NSIDC sea-ice records that NASA itself uses on its Vital Signs pages). Raw extracts and the scripts that turn them into the app\'s files are in the repository (`scripts/raw/`, `scripts/build-snapshots.mjs`). No value was typed in by hand or smoothed.',
  dmSampling: 'Sampling',
  dmToSound: 'To sound',
  dmFireTitle: 'Wildfires',
  dmRainTitle: 'Rain',
  dmOceanTitle: 'Ocean heat',
  dmOtherTitle: 'Other tracks',
  dmStereoTitle: 'Where on Earth, and what the stereo means',
  dmFireSource: 'NASA FIRMS, VIIRS S-NPP 375 m near-real-time active fire detections (requires a free FIRMS map key; `npm run fetch:firms`).',
  dmFireSampling: 'World, 2–7 Oct 2026. Detections grouped into 2° cells; the value is the maximum fire radiative power (MW) in the cell; the 80 strongest cells are kept. The Atlas plays 2–5 Oct, the days every daily layer shares.',
  dmFireSound: '`{f}`. Higher values give faster crackles (4–20 per second) and a brighter filter (800–3000 Hz).',
  dmRainSource: 'NASA POWER Daily API v2.10, `PRECTOTCORR` (bias-corrected precipitation from MERRA-2), mm/day.',
  dmRainSampling: 'A 10° global grid, 396 points from 50°S to 50°N, all fetched. The 48 points with the highest single-day rain during 2–5 Oct are kept, so this layer is a sample of wet places, not a full rain map. The Frame Jukebox shows the full GPM IMERG rain image.',
  dmRainSound: '`{f}`. Higher values give denser droplets (about 3–18 per second) at higher pitch (340–700 Hz).',
  dmOceanSource: 'NASA JPL MUR sea surface temperature anomaly, monthly (ERDDAP dataset `jplMURSST41anommday`, NOAA CoastWatch), September 2026.',
  dmOceanSampling: '1° grid, 32,095 valid ocean cells. Cells within 3° of land or ice and beyond 58° latitude are skipped. The 40 most anomalous cells are chosen with at least 12° between them, so both warm and cold extremes around the world are heard.',
  dmOceanGlobal: 'Across all valid cells the area-weighted mean anomaly is +{mean} °C and {pct}% of the ocean was warmer than normal.',
  dmOceanSound: 'A sustained drone at 110 Hz shifted by 4 semitones per 3 °C of anomaly; `{f}` sets brightness. Warm cells are pink, cold cells blue. Monthly product, so it does not change between days.',
  dmFramesKey: 'NASA image frames',
  dmFramesBody: 'NASA GIBS (Worldview) WMS images requested live for the same week: VIIRS true colour, VIIRS thermal anomalies, GPM IMERG rain rate, MUR SST anomaly, OMI NO₂, MODIS aerosol, MODIS NDVI, VIIRS night lights. The needle reads pixel brightness and colour, so this track sonifies the picture, not calibrated values.',
  dmBdKey: 'Bangladesh',
  dmBdBody: 'NASA POWER daily `PRECTOTCORR` for 8 divisional cities, 1 Jun–5 Oct 2026 and the same days of 2025, compared with POWER\'s 2001–2020 monthly climatology. Model-based estimates for roughly 50 km cells, not rain-gauge readings.',
  dmVitalKey: 'Vital signs',
  dmVitalBody: 'NASA GISS GISTEMP v4 global annual anomaly (1880–2025, vs 1951–1980); NOAA GML Mauna Loa annual CO₂ (1959–2025), the record on NASA\'s Vital Signs page; NSIDC Sea Ice Index v4.0 Arctic September extent (1979–2026; 2025–26 near-real-time). Raw files in `scripts/raw/`. "Your data" plays any two-column CSV locally in the browser.',
  dmPlaceKey: 'Any place',
  dmPlaceBody: 'Clicking the globe asks the NASA POWER monthly API live for that point (T2M and PRECTOTCORR, 1981–2025) and plays one note per year. The trend is a least-squares slope. Values are model-based for a roughly 50 km cell.',
  dmStereoBody: 'Pan = longitude ÷ 180, so 180°W is hard left and 180°E hard right. In 3D (HRTF) mode latitude also lifts the sound up or down. Place names come from Natural Earth country shapes; ocean cells get the name of their basin. A 12-voice limit keeps the mix clear: the strongest values in the enabled layers are the ones you hear.',
  dmCredit: 'This is an independent Space Apps entry, not an official NASA product. Imagery and data courtesy of NASA ESDIS, FIRMS, LaRC POWER, JPL PO.DAAC (via NOAA CoastWatch ERDDAP), GISS and GIBS. Globe texture: three.js example maps.',
  afmLabel: 'Audio-First Earth Science Exploration Mode',
  afmList: 'Observation list',
  afmListNote: 'Every observation for this day as a readable list, for screen readers and keyboard users. Each row plays its own sound at its real position.',
  afmSwitch: 'Switch to Visual 3D',
  afmShow: 'Show:',
  afmFires: 'Fires Only',
  afmPrecip: 'Precipitation Only',
  afmOcean: 'Ocean SST Only',
  afmTab: 'Tab to a row, Enter to hear it',
  afmNow: 'Currently Sonifying',
  afmPlay: 'Play Audio for Location',
  closePlace: 'Close place',
  chooseCity: 'Choose a city',
  dayLabel: 'Day',
  tourRegion: 'Guided tour',
  tourNext: 'Next step',
  tourEnd: 'End tour',
  mapLabel: 'World map of the observations. Use the arrow keys to move the focus point and press Enter or Space to hear the nearest observation.',
  zoomIn: 'Zoom In',
  zoomOut: 'Zoom Out',
  resetMap: 'Reset Map View',
  nearestObs: 'Nearest Observation:',
  frSeeEarthGov: 'See it on earth.gov',
  frLive: 'Live from NASA GIBS, same week as the Atlas data',
  frThen: 'Then and now',
  frHow: 'How the image becomes sound',
  frChoose: 'Choose an image',
  srcLine: 'Source: {c}.',
  seriesLabel: 'Series',
  spaceAppsLogoAlt: 'NASA Space Apps Challenge logo',
};

export type StringKey = keyof typeof en;

const bn: Partial<Record<StringKey, string>> = {
  appName: 'সনিক আর্থ অ্যাটলাস',
  tagline: 'পৃথিবীর তথ্যের জুকবক্স',
  heroLead: 'নাসার আসল পৃথিবী পর্যবেক্ষণ আর স্যাটেলাইট ছবি, শব্দ হয়ে বাজে। একটা ট্র্যাক বেছে নিন, হেডফোন পরুন, শুনুন কোথায় আগুন জ্বলছে, বৃষ্টি হচ্ছে, সমুদ্র গরম হচ্ছে।',
  heroNote: 'প্রতিটি শব্দ ডেটা থেকে সরাসরি তৈরি হয়। কিছুই আগে থেকে রেকর্ড করা নয়।',
  heroHeadphones: 'হেডফোন ভালো: বাম-ডান শব্দ দ্রাঘিমাংশ অনুসরণ করে।',
  pickTrack: 'একটা ট্র্যাক বাছুন',
  startTour: '৪০ সেকেন্ডের ট্যুর চালান',
  listenNow: 'এখনই শুনুন',
  audioBlocked: 'আপনার ব্রাউজার শব্দ আটকে দিয়েছে। আবার চালান চাপুন, ভলিউম দেখুন আর সাইলেন্ট মোড বন্ধ করুন।',
  tryEic: 'এর বদলে সাথে থাকা একটি আর্থ ইনফরমেশন সেন্টার ফ্রেম চালান',
  exploreSilently: 'শব্দ ছাড়া দেখুন',
  track1: 'এই সপ্তাহের পৃথিবী',
  track1Desc: '২–৫ অক্টোবর ২০২৬-এর আগুন, বৃষ্টি আর সমুদ্রের তাপ, আপনার চারপাশে স্টেরিওতে।',
  track2: 'EIC ফ্রেম ও নাসার ছবি',
  track2Desc: 'নাসার আর্থ ইনফরমেশন সেন্টারের ছবি ও একই দিনের স্যাটেলাইট ছবি, বাম থেকে ডানে স্ক্যান হয়ে শব্দ হয়।',
  track3: 'বাংলাদেশের বর্ষা',
  track3Desc: '৮ বিভাগের দৈনিক বৃষ্টি, জুন–অক্টোবর ২০২৬, ২০২৫ আর ২০ বছরের গড়ের সাথে।',
  track4: 'পৃথিবীর প্রাণচিহ্ন',
  track4Desc: '১৮৮০ থেকে বৈশ্বিক তাপমাত্রা, ১৯৫৯ থেকে CO₂, ১৯৭৯ থেকে আর্কটিক বরফ, প্রতি বছর একটি সুর, আলাদা বা একসাথে। নিজের CSV-ও বাজাতে পারেন।',
  anyPlace: 'যেকোনো জায়গা',
  tracks: 'ট্র্যাক',
  globe: 'গ্লোব',
  map: 'মানচিত্র',
  list: 'তালিকা',
  soundOn: 'শব্দ চালু',
  soundOff: 'শব্দ বন্ধ',
  tour: 'ট্যুর',
  data: 'ডেটা ও পদ্ধতি',
  settings: 'সেটিংস',
  home: 'হোম',
  layers: 'স্তর',
  fire: 'দাবানল',
  rain: 'বৃষ্টি',
  ocean: 'সমুদ্রের তাপ',
  fireUnit: 'আগুনের শক্তি, মেগাওয়াট',
  rainUnit: 'দৈনিক বৃষ্টি, মিমি',
  oceanUnit: 'তাপমাত্রার বিচ্যুতি, °সে',
  fireSound: 'চটচট শব্দ',
  rainSound: 'ফোঁটা',
  oceanSound: 'গুঞ্জন',
  hear: 'শুনুন',
  nowHearing: 'আপনি কী শুনছেন',
  nothingPlaying: 'ডেটা শুনতে শব্দ চালু করুন। নিচের প্রতিটি কণ্ঠ একটি আসল পর্যবেক্ষণ।',
  loudest: 'এখন সবচেয়ে জোরালো',
  left: 'বামে',
  right: 'ডানে',
  centre: 'মাঝে',
  rising: 'বাড়ছে',
  falling: 'কমছে',
  steady: 'স্থির',
  vsYesterday: 'আগের দিনের তুলনায়',
  pitch: 'সুর',
  rate: 'স্পন্দন/সে',
  pan: 'অবস্থান',
  hearChange: 'পরিবর্তন শুনুন',
  hearChangeHint: 'আগের দিনের চেয়ে যেখানে বেড়েছে সেখানে শব্দ জোরালো ও দ্রুত',
  play: 'চালান',
  legend: 'নির্দেশিকা',
  loudness: 'জোর',
  whatHearing: 'আমি কী শুনছি?',
  hearNeedle: 'সুই হলো খাড়া দাগ। এটি পশ্চিম থেকে পূর্বে, বাম থেকে ডানে যায়, আর তার নিচের ছবির অংশের শব্দ শোনা যায়।',
  hearPitch: 'উচ্চতা মানে সুর: ছবির উপরের অংশে সবচেয়ে চড়া সুর, নিচে সবচেয়ে খাদ। মোট ১২টি স্তর।',
  hearLoud: 'উজ্জ্বলতা মানে জোর: উজ্জ্বল পিক্সেল জোরে, গাঢ় পিক্সেল নীরব।',
  hearColour: 'রং মানে ধ্বনির ধরন: লাল-কমলা ঝাঁঝালো, নীল-সবুজ নরম।',
  hearScrub: 'সুইয়ের স্লাইডার টানুন বা ছবিতে ক্লিক করুন, যেকোনো একটি জায়গার শব্দ শুনতে। ছবির উপর টেনে একটি অংশ বারবার শুনুন।',
  shareLink: 'লিংক কপি',
  linkCopied: 'লিংক কপি হয়েছে',
  story: 'EIC গল্প চালান',
  storyStop: 'গল্প থামান',
  storyNext: 'পরেরটি',
  chooseAny: 'যেকোনো দুটি বেছে নিন',
  leftEar: 'বাম কান',
  rightEar: 'ডান কান',
  describeFrame: 'ছবিটির বর্ণনা',
  scrub: 'সুইয়ের অবস্থান',
  scrubHint: 'টেনে বা অ্যারো কী দিয়ে ছবির যেকোনো অংশ শুনুন। ছবিতে ক্লিক বা ট্যাপ করলে সেই জায়গার শব্দ শোনা যাবে।',
  loop: 'বারবার',
  speed: 'গতি',
  loopStart: 'এখান থেকে শুরু',
  loopEnd: 'এখানে শেষ',
  clearRegion: 'পুরো ছবি',
  regionHint: 'ছবির উপর টেনে শুধু সেই অংশ বারবার শুনুন।',
  pause: 'থামান',
  prevDay: 'আগের দিন',
  nextDay: 'পরের দিন',
  record: '৩০ সেকেন্ড রেকর্ড',
  recording: 'রেকর্ড হচ্ছে… {s} সে',
  recordSaved: '{name} সংরক্ষিত',
  language: 'ভাষা',
  reduceMotion: 'কম অ্যানিমেশন',
  highContrast: 'উচ্চ কনট্রাস্ট',
  narration: 'কণ্ঠে বর্ণনা',
  calmBackground: 'পটভূমির নড়াচড়া থামান',
  calmBackgroundNote: 'তারার পটভূমি, গ্লোবের নিজে ঘোরা ও মেঘের সরে যাওয়া থামে। নির্দিষ্ট জায়গায় যাওয়া, শব্দ বাজানো ও বাকি সব চলবে।',
  diagnostics: 'পারফরম্যান্স ডায়াগনস্টিকস',
  srNote: 'স্ক্রিন রিডার: প্রতিটি দৃশ্যে শিরোনাম ও সরাসরি বর্ণনা আছে। তালিকা দৃশ্যে প্রতিটি পর্যবেক্ষণ টেবিলের সারি হিসেবে পড়া হয়; শুনতে সারিতে Enter চাপুন। ডেটা জুকবক্সে “আপনি যা শুনছেন” অংশ প্রতিটি শব্দ লেখায় ব্যাখ্যা করে।',
  spatial: 'স্থানিক শব্দ',
  stereo: 'স্টেরিও',
  hrtf: '৩ডি (HRTF)',
  volume: 'ভলিউম',
  shortcuts: 'কিবোর্ড শর্টকাট',
  close: 'বন্ধ',
  realData: 'নাসার আসল ডেটা',
  bdLens: 'বাংলাদেশ',
  monsoonTitle: 'বাংলাদেশের বর্ষা ২০২৬',
  monsoonLead: 'প্রতিটি বিভাগ একটি কণ্ঠ। পশ্চিম বামে, পূর্ব ডানে, উত্তর উঁচু সুরে। বেশি বৃষ্টি মানে ঘন ও জোরালো ফোঁটা।',
  compare2025: '২০২৫-এর সাথে তুলনা',
  totalSince: '১ জুন থেকে মোট',
  ofNormal: '২০০১–২০২০ গড়ের',
  wettest: 'সবচেয়ে ভেজা দিন',
  pulseTitle: '১৪৬ বছরের বৈশ্বিক উষ্ণায়ন',
  pulseLead: 'প্রতি বছর একটি সুর। ১৯৫১–১৯৮০-র তুলনায় পৃথিবী যত গরম, সুর তত উঁচু।',
  framesTitle: 'আর্থ ইনফরমেশন সেন্টারের ফ্রেম',
  framesLead: 'একটি সুই নাসার স্যাটেলাইট ছবি পশ্চিম থেকে পূর্বে স্ক্যান করে। উচ্চতা = সুর, উজ্জ্বলতা = জোর, রং = ধ্বনির ধরন।',
  beforeAfter: 'আগে / পরে',
  beforeAfterHint: 'বাম কানে প্রথম ছবি, ডান কানে দ্বিতীয় ছবি, একই সময়ে।',
  loadOwn: 'নিজের EIC ছবি দিন',
  eicGroup: 'নাসা আর্থ ইনফরমেশন সেন্টার (earth.gov)',
  imagery: 'নাসার ছবি',
  imageryHint: 'নির্বাচিত দিনের নাসার স্যাটেলাইট ছবি গ্লোবে দেখান',
  dataFrom: 'ডেটার উৎস',
  listenHere: 'এখানে শুনুন',
  noObs: 'এখানে লোড করা ডেটায় কোনো পর্যবেক্ষণ নেই।',
  skip: 'মূল অংশে যান',
  mainNav: 'প্রধান',
  navExplore: 'পৃথিবী ঘুরে দেখুন',
  loadingGlobe: 'গ্লোব লোড হচ্ছে…',
  loadingView: 'লোড হচ্ছে…',
  viewGroup: 'দৃশ্য',
  navJukebox: 'ডেটা জুকবক্স',
  navAbout: 'বিজ্ঞানের কথা',
  collections: 'সংগ্রহ',
  menu: 'মেনু',
  playingNow: 'বাজছে: {label}',
  pausePlayback: '{label} থামান',
  heroKicker: 'নাসা স্পেস অ্যাপস চ্যালেঞ্জ ২০২৬ · আর্থ ইনফরমেশন জুকবক্স · স্বাধীন দলের প্রকল্প, নাসার অফিসিয়াল পণ্য নয়',
  heroHeadline: 'বদলে যাওয়া পৃথিবীকে শুনুন',
  heroDataLine: 'সনিক আর্থ অ্যাটলাস নাসার আসল পৃথিবী-ডেটাকে শব্দে রূপ দেয়, যা আপনি ঘুরে ঘুরে শুনতে পারেন। প্রতিটি মান হয়ে যায় একটি সুর, একটি ছন্দ আর হেডফোনে একটি অবস্থান।',
  ctaExplore: 'গ্লোব ঘুরে দেখুন',
  ctaStory: 'একটি ডেটা-গল্প শুনুন',
  scrollHint: 'কীভাবে কাজ করে দেখতে নিচে যান',
  splitTitle: 'এক পৃথিবী, অনেক পরিমাপ',
  splitBody: 'স্যাটেলাইট আর মডেল প্রতিদিন আগুন, বৃষ্টি, সমুদ্রের তাপ, তাপমাত্রা, কার্বন ডাই অক্সাইড আর সমুদ্র-বরফ মাপে। আমরা প্রতিটি মান, তার একক আর উৎস রেখে দিই এবং প্রকাশিত নিয়মে বাজাই, যাতে আপনি একটি ধরন শুনে মানচিত্রে মিলিয়ে দেখতে পারেন।',
  splitPoint1: 'নাসা FIRMS, POWER, MUR SST, GISTEMP ও GIBS-এর আসল স্ন্যাপশট, তারিখসহ',
  splitPoint2: 'প্রতিটি ডেটাসেটের একটি নিয়ম, শব্দের পাশেই দেখানো',
  splitPoint3: 'কান, কিবোর্ড ও স্ক্রিন রিডারে চলে, বাংলা ও ইংরেজিতে',
  immersiveTitle: 'ঘোরান, তারপর শুনুন',
  immersiveBody: 'গ্লোব টেনে ঘোরান। যেকোনো জায়গায় ক্লিক করে তার ৪৫ বছরের তাপমাত্রা আর বৃষ্টি শুনুন, অথবা চার দিনের আগুন, বৃষ্টি আর সমুদ্রের তাপ ধাপে ধাপে শুনুন।',
  immersiveCta: 'শুরু করুন',
  // Landing carousel (Phase 9)
  carouselLabel: 'পৃথিবীর একটি রূপ বেছে নিন',
  carouselOf: '{total}-এর মধ্যে {n}: {name}',
  ctaStart: 'শুরু করুন',
  ctaLearn: 'আরও জানুন',
  ctaPreview: 'ছোট একটি নমুনা বাজান',
  ctaStopPreview: 'নমুনা থামান',
  ctaOpenTrack: 'এই ট্র্যাক খুলুন',
  ctaBackLevel: 'ফিরে যান',
  carPrev: 'আগের পৃথিবী: {name}',
  carNext: 'পরের পৃথিবী: {name}',
  carGoTo: '{name} দেখান',
  carHowItWorks: 'কীভাবে কাজ করে দেখুন',
  previewNote: 'নমুনাটি এই কার্ডের মান থেকে তৈরি একটি ছোট সুর: মান যত বেশি, সুর তত উঁচু।',
  levelOverview: 'সংক্ষিপ্ত রূপ',
  levelDetail: 'বিস্তারিত',
  levelImmersive: 'গভীর দৃশ্য',
  mFires: '{date}-এ আগুন শনাক্ত',
  mStrongest: 'সবচেয়ে তীব্র আগুন ({unit})',
  mFrames: 'বাজানোর মতো আর্থ ইনফরমেশন সেন্টারের ছবি',
  mCities: 'বাংলাদেশের শহর',
  mSylhet: 'মিমি বৃষ্টি সিলেটে, {from} থেকে {to}',
  mAnomaly: '°সে {year} সালে, ১৯৫১–১৯৮০ সালের গড়ের তুলনায়',
  mYears: 'বছরের রেকর্ড, ১৮৮০ থেকে',
  metricsLabel: 'মূল সংখ্যা',
  planetCredit: 'গ্রহ: ত্রিমাত্রিক গোলকে নাসার ব্লু মার্বেল ছবি।',
  w1Kicker: 'A1 · এই সপ্তাহের পৃথিবী',
  w1Name: 'আগুন',
  w1Line: '২–৫ অক্টোবর ২০২৬-এ পৃথিবী কোথায় জ্বলেছে, স্টেরিওতে আপনার চারপাশে।',
  w1Title: 'জ্বলতে থাকা পৃথিবী',
  w1Body: 'নাসার FIRMS স্যাটেলাইট দিনে কয়েকবার সক্রিয় আগুন শনাক্ত করে। প্রতিটি আগুন একটি সুর: বেশি গরম আগুনের সুর উঁচু, আর দ্রাঘিমাংশ ঠিক করে সেটি হেডফোনের বামে না ডানে। এটি ২–৫ অক্টোবর ২০২৬-এর চার দিনের একটি স্ন্যাপশট।',
  w1Deep: 'প্রতিটি বিন্দু স্যাটেলাইটে ধরা পড়া তাপের অস্বাভাবিকতা, নিশ্চিত দাবানল নয়: সেটি ফসলের নাড়া পোড়ানো, গ্যাস ফ্লেয়ার বা আগ্নেয়গিরিও হতে পারে। অ্যাটলাসে গ্লোব ঘুরিয়ে, দেশ বেছে চার দিন ধরে আগুনের সরে যাওয়া শুনতে পারেন।',
  w1Src: 'ডেটা: নাসা FIRMS সক্রিয় আগুন, স্ন্যাপশট ২–৫ অক্টোবর ২০২৬।',
  w1Pic: 'ছবি: নাসা GIBS VIIRS আসল রঙ, ৩ অক্টোবর ২০২৬।',
  w2Kicker: 'A2 · EIC ফ্রেম ও নাসার ছবি',
  w2Name: 'ছবি',
  w2Line: 'স্যাটেলাইটের ছবি শব্দ হয়ে বাজে, একবারে একটি সুইপে।',
  w2Title: 'মহাকাশ থেকে দেখা পৃথিবী',
  w2Body: 'আর্থ ইনফরমেশন সেন্টারের মানচিত্র আর নাসার স্যাটেলাইট ছবি ছবিটি স্ক্যান করে শব্দ হয়: গাঢ় আর উজ্জ্বল অংশ সুর ও জোর বদলায়, আর ছবির কোন জায়গা তা ঠিক করে বাম-ডান। একটি ফ্রেম বেছে সুইপটি শুনুন।',
  w2Deep: 'ছবি আসলে সংখ্যার ছক। আমরা একটি পথ ধরে পিক্সেল পড়ি, প্রকাশিত নিয়মে বাজাই, আর রঙের ব্যাখ্যা, তারিখ ও কৃতজ্ঞতা শব্দের পাশেই রাখি। যে অংশে ডেটা নেই সেখানে নীরব থাকে।',
  w2Src: 'পদ্ধতি: আর্থ ইনফরমেশন সেন্টার ও নাসা GIBS ছবির পিক্সেল সুইপ (পরিচিতি দেখুন)।',
  w2Pic: 'ছবি: নাসা GIBS VIIRS আসল রঙ, ৩ অক্টোবর ২০২৬।',
  w3Kicker: 'B1 · বাংলাদেশের বর্ষা',
  w3Name: 'বর্ষা',
  w3Line: 'আটটি শহরে একটি গ্রীষ্মের বৃষ্টি, স্বাভাবিক বছরের পাশে।',
  w3Title: 'বৃষ্টির পৃথিবী',
  w3Body: 'বাংলাদেশে বেশিরভাগ বৃষ্টি হয় জুন থেকে সেপ্টেম্বরে। আমরা আটটি শহরের নাসা POWER-এর দৈনিক বৃষ্টি বাজাই ২০০১–২০২০ সালের গড়ের পাশে, যাতে ভেজা দিনটি স্বাভাবিক দিন থেকে আলাদা শোনা যায়।',
  w3Deep: 'নাসা POWER (MERRA-2 ভিত্তিক) থেকে ১ জুন ২০২৬ থেকে দৈনিক বৃষ্টিপাত, ২০০১–২০২০ সালের মাসিক গড়ের সঙ্গে তুলনা করে। বেশি বৃষ্টির দিন জোরালো ও ঘন শোনায়। এটি মডেল-নির্ভর পুনর্বিশ্লেষণ, বৃষ্টিমাপক যন্ত্রের পাঠ নয়।',
  w3Src: 'ডেটা: আটটি শহরের নাসা POWER দৈনিক বৃষ্টি ও ২০০১–২০২০ জলবায়ু গড়।',
  w3Pic: 'ছবি: নাসা GEOS বৃষ্টি, আর্থ ইনফরমেশন সেন্টার।',
  w4Kicker: 'B2 · পৃথিবীর প্রাণচিহ্ন',
  w4Name: 'উষ্ণায়ন',
  w4Line: 'একশো বছরেরও বেশি বৈশ্বিক তাপমাত্রা, একটি ক্রমে উঠতে থাকা সুরে।',
  w4Title: 'উষ্ণ হতে থাকা পৃথিবী',
  w4Body: 'নাসা GISTEMP প্রতি বছরের জন্য একটি সংখ্যা দেয়: বৈশ্বিক তাপমাত্রা ১৯৫১–১৯৮০ সালের গড় থেকে কতটা আলাদা। আমরা ১৮৮০ থেকে সর্বশেষ বছর পর্যন্ত সুর হিসেবে বাজাই, তাই ঠান্ডা বছর নিচে আর গরম বছর উপরে শোনায়।',
  w4Deep: 'প্রতিটি মান স্থল ও সমুদ্রের বার্ষিক বিচ্যুতি, °সে-তে, ১৯৫১–১৯৮০ ভিত্তির তুলনায়, তাই প্রতিটি সুর একটি পূর্ণ বছর। নীল বছর ভিত্তির নিচে, গোলাপি বছর উপরে। অন্য ধারার সঙ্গে তুলনা করতে ট্র্যাকটি খুলুন।',
  w4Src: 'ডেটা: নাসা GISS GISTEMP v4, স্থল ও সমুদ্রের বার্ষিক বিচ্যুতি।',
  w4Pic: 'ছবি: সমুদ্রের তাপ, আর্থ ইনফরমেশন সেন্টার।',
  howTitle: 'ডেটা কীভাবে শব্দ হয়',
  how1: 'নাসার ডেটা',
  how1d: 'FIRMS, POWER, MUR, GISTEMP, GIBS থেকে আসল মান',
  how2: 'স্কেল',
  how2d: 'প্রতিটি মান ০ থেকে ১-এ, লেখা সূত্রে',
  how3: 'সংশ্লেষণ',
  how3d: 'ব্রাউজারে Web Audio দিয়ে সরাসরি শব্দ',
  how4: 'শুনুন ও দেখুন',
  how4d: 'অবস্থান, মান আর শব্দ একসাথে ব্যাখ্যা করা',
  globeStill: 'মহাকাশ থেকে পৃথিবী। এই ডিভাইসে ৩ডি গ্লোব চালু হয়নি, তাই একটি স্থির ছবি দেখানো হচ্ছে।',
  webglOff: 'এই ডিভাইসে ৩ডি গ্লোব চালু হয়নি, তাই সমতল মানচিত্র দেখানো হচ্ছে।',
  footerSonification: 'এখানের প্রতিটি শব্দ আপনার ব্রাউজারে ডেটা থেকে তৈরি (ডেটা সনিফিকেশন), কোনো রেকর্ডিং নয়।',
  footerNotNasa: 'নাসা স্পেস অ্যাপস চ্যালেঞ্জ ২০২৬-এর স্বাধীন প্রকল্প, নাসার অফিসিয়াল পণ্য নয়।',
  footerCredits: 'ডেটা ও ছবি: নাসা ESDIS, FIRMS, LaRC POWER, JPL PO.DAAC (NOAA CoastWatch ERDDAP হয়ে), GISS, GIBS ও আর্থ ইনফরমেশন সেন্টার, সাথে NOAA GML ও NSIDC।',
  footerSources: 'উৎস',
  footerRepo: 'GitHub-এ সোর্স কোড',
  aboutTitle: 'বিজ্ঞানের কথা',
  aboutLead: 'সনিক আর্থ অ্যাটলাস কীভাবে পরিমাপকে শব্দে রূপ দেয়, প্রতিটি সংখ্যা কোথা থেকে আসে, আর এটি কী বলতে পারে না।',
  aboutHowTitle: 'সনিফিকেশন কীভাবে কাজ করে',
  aboutHowP1: 'সনিফিকেশন মানে ডেটাকে শব্দ হিসেবে বাজানো। এখানে প্রতিটি পর্যবেক্ষণ প্রথমে একটি নির্দিষ্ট সূত্রে ০ থেকে ১-এর মধ্যে একটি সংখ্যায় আনা হয়। সেই সংখ্যা শব্দের এক বা একাধিক গুণ ঠিক করে: সুর, জোর, ছন্দ, উজ্জ্বলতা বা স্টেরিও অবস্থান।',
  aboutHowP2: 'প্রতিটি ডেটাসেটের নিয়ম স্থির, তাই একই ডেটা সবসময় একই শব্দ দেয়। দ্রাঘিমাংশ স্টেরিও অবস্থান ঠিক করে (১৮০° পশ্চিম একদম বামে, ১৮০° পূর্ব একদম ডানে)। কিছুই আগে থেকে রেকর্ড করা নয়: আপনি শোনার সময় ব্রাউজার Web Audio দিয়ে প্রতিটি শব্দ তৈরি করে।',
  aboutMappingTitle: 'ম্যাপিং টেবিল',
  aboutMappingLead: 'অ্যাটলাসের তিনটি স্তর, অ্যাপে ব্যবহৃত হুবহু সূত্রসহ।',
  aboutSeriesTitle: 'ডেটা জুকবক্সের সারি',
  aboutSeriesLead: 'প্রতিটি সারি একটি নির্দিষ্ট পরিসরে বসানো, যা সব সময়কাল ও দেশে একই, আর G-মেজর পেন্টাটনিক স্কেলে G3 (১৯৬ Hz) থেকে G5 (৭৮৪ Hz) পর্যন্ত বাজে। আগের মানের চেয়ে বড় পরিবর্তনে বেশি স্পন্দন (১–৬)। মান না থাকলে নীরবতা।',
  colSeries: 'সারি',
  colRange: 'নির্দিষ্ট পরিসর',
  colBaseline: 'ভিত্তি',
  aboutSqrt: 'বর্গমূল স্কেল',
  colLayer: 'স্তর',
  colVariable: 'চলক ও একক',
  colResolution: 'রেজোলিউশন',
  colToNumber: 'মান থেকে ০–১',
  colToSound: 'শব্দে',
  aboutTracksTitle: 'অন্য ট্র্যাকগুলো',
  aboutTrackFrames: 'একটি সুই প্রতিটি ছবি পশ্চিম থেকে পূর্বে স্ক্যান করে। ছবির উচ্চতা = সুর (১২টি পেন্টাটনিক স্তর), উজ্জ্বলতা = জোর, রং = ধ্বনির ধরন। এটি ছবিকে বাজায়, মাপা মানকে নয়।',
  aboutTrackMonsoon: '৮টি বিভাগের প্রতিটি একটি কণ্ঠ। পশ্চিম বামে, পূর্ব ডানে, উত্তর উঁচু সুরে। দৈনিক বৃষ্টি বেশি হলে ফোঁটা ঘন ও জোরালো।',
  aboutTrackPulse: 'প্রতি বছর একটি সুর। উঁচু সুর মানে উষ্ণ বছর, বেশি CO₂ বা বেশি সমুদ্র-বরফ। তিনটি একসাথে একটি কর্ড হিসেবেও বাজতে পারে।',
  aboutSourcesTitle: 'ডেটার উৎস',
  srcFirms: 'সক্রিয় আগুন শনাক্তকরণ, VIIRS ৩৭৫ মি, স্ন্যাপশট ২–৭ অক্টোবর ২০২৬',
  srcPower: 'দৈনিক ও মাসিক বৃষ্টি ও তাপমাত্রা (MERRA-2 ভিত্তিক), ১৯৮১–২০২৫ ও ২০২৬-এর স্ন্যাপশট',
  srcMur: 'মাসিক সমুদ্রপৃষ্ঠের তাপমাত্রার বিচ্যুতি, সেপ্টেম্বর ২০২৬',
  srcGistemp: 'বৈশ্বিক বার্ষিক তাপমাত্রার বিচ্যুতি, ১৮৮০–২০২৫, ১৯৫১–১৯৮০-র তুলনায়',
  srcGml: 'মাউনা লোয়ার বার্ষিক CO₂, ১৯৫৯–২০২৫',
  srcNsidc: 'সেপ্টেম্বরে আর্কটিক সমুদ্র-বরফের বিস্তার, ১৯৭৯–২০২৬',
  srcGibs: 'সরাসরি আনা দৈনিক স্যাটেলাইট ছবি (প্রকৃত রং, তাপীয় বিচ্যুতি, বৃষ্টির হার ইত্যাদি)',
  srcEic: 'আর্থ ইনফরমেশন সেন্টারের ফ্রেম, কৃতজ্ঞতাসহ সাথে দেওয়া',
  aboutLimitsTitle: 'সীমাবদ্ধতা',
  limit1: 'অ্যাটলাসের স্তরগুলো কয়েক দিনের স্ন্যাপশট, সরাসরি ফিড নয়। প্রতিটি স্তরের সাথে তারিখ দেখানো হয়।',
  limit2: 'বৃষ্টির বিন্দুগুলো সবচেয়ে ভেজা গ্রিড-বিন্দুর নমুনা, পূর্ণ বৃষ্টির মানচিত্র নয়।',
  limit3: 'নাসা POWER-এর মান প্রায় ৫০ কিমি ঘরের মডেল-অনুমান, বৃষ্টিমাপক বা স্টেশনের পাঠ নয়।',
  limit4: 'আগুনের মান ২° ঘরে ভাগ করা, প্রতিটি ঘরে শুধু সবচেয়ে শক্তিশালী শনাক্তকরণ রাখা হয়।',
  limit5: 'ছবির সনিফিকেশন পিক্সেলের রং ও উজ্জ্বলতা পড়ে, তাই এটি ছবির মতোই নির্ভুল।',
  limit6: 'শব্দ ছবিকে সাহায্য করে, সংখ্যার বদলে নয়; সংখ্যা সবসময় লেখাতেও দেখানো হয়।',
  aboutA11yTitle: 'অ্যাক্সেসিবিলিটি নিয়ন্ত্রণ',
  a11y1: 'কিবোর্ড: S শব্দ, Space চালান, ← → দিন, 1 2 3 স্তর, G M L দৃশ্য, T ট্যুর, ? সেটিংস।',
  a11y2: 'তালিকা দৃশ্য প্রতিটি পর্যবেক্ষণ লেখায় পড়ে শোনায়, অবস্থান, মান ও শব্দসহ।',
  a11y3: 'সেটিংস: বাংলা বা ইংরেজি, কম অ্যানিমেশন, উচ্চ কনট্রাস্ট, কণ্ঠে বর্ণনা, স্টেরিও বা ৩ডি শব্দ, ভলিউম।',
  a11y4: '৩ডি গ্লোব চালু না হলে সমতল মানচিত্র বা স্থির ছবি দেখানো হয়, বাকি সব কাজ করে।',
  aboutCreditsTitle: 'কৃতজ্ঞতা',
  aboutCredits: 'নাসা স্পেস অ্যাপস চ্যালেঞ্জ ২০২৬-এর জন্য একটি স্বাধীন দলের তৈরি। গ্লোবের টেক্সচার three.js উদাহরণ থেকে। দেশের আকার Natural Earth (world-atlas) থেকে। ফন্ট: Bricolage Grotesque, IBM Plex Sans ও Noto Sans Bengali।',
  fullMethod: 'ডেটা ও পদ্ধতির পূর্ণ বিবরণ',
  readAbout: 'বিজ্ঞানের কথা পড়ুন',
  country: 'দেশ',
  countrySearch: 'দেশ খুঁজুন',
  countryPlaceholder: 'দেশের নাম লিখুন…',
  countryResults: '{n}টি দেশ পাওয়া গেছে',
  countryNone: '“{q}” নামে কোনো দেশ নেই',
  countrySelected: 'নির্বাচিত দেশ',
  countryNoneSelected: 'কোনো দেশ নির্বাচিত নয়। খুঁজুন, বা গ্লোব কিংবা মানচিত্রে ক্লিক করুন।',
  countryClear: 'দেশ সরান',
  countryPoint: 'প্রতিনিধি বিন্দু',
  countryPointNote: 'সবচেয়ে বড় ভূখণ্ডের কেন্দ্র, বিন্দু-ডেটার জন্য ব্যবহৃত। পুরো দেশের গড় নয়।',
  countryChosen: '{name} নির্বাচিত',
  countryCleared: 'দেশ সরানো হয়েছে',
  countryHover: '{name}, নির্বাচন করতে ক্লিক করুন',
  countryOcean: 'খোলা সমুদ্র, এখানে কোনো দেশ নেই',
  countryUnderFocus: 'ফোকাস বিন্দুর দেশ',
  countrySelectKey: 'নির্বাচন করতে C চাপুন',
  resetView: 'দৃশ্য রিসেট',
  selectedBadge: 'নির্বাচিত',
  provSource: 'উৎস',
  provVariable: 'রাশি',
  provUnit: 'একক',
  provPeriod: 'সময়কাল',
  provSpatial: 'স্থানিক রেজোলিউশন',
  provTemporal: 'সময়ের রেজোলিউশন',
  provCredit: 'কৃতজ্ঞতা',
  provSnapshot: 'স্ন্যাপশট {date}',
  provSnapshotNoDate: 'স্ন্যাপশট',
  provLive: 'লাইভ',
  provContext: 'বৈশ্বিক প্রেক্ষাপট',
  provSample: 'নমুনা',
  provMethod: 'পদ্ধতি ও সীমা',
  provMethodHead: 'পদ্ধতি',
  provLimitsHead: 'সীমাবদ্ধতা',
  provOpenSource: 'উৎস পাতা খুলুন',
  dsLoading: 'লোড হচ্ছে…',
  dsEmpty: 'এখানে দেখানোর মতো কিছু নেই।',
  dsStale: 'এই ডেটা পুরোনো হতে পারে।',
  dsError: 'এই ডেটা আনা যায়নি।',
  dsOffline: 'আপনি অফলাইন মনে হচ্ছে।',
  dsRetry: 'আবার চেষ্টা করুন',
  profileSample: 'অফলাইন নমুনা চলছে, তাই দেশের কোনো আসল সংখ্যা দেখানো হচ্ছে না।',
  profileTitle: 'বিজ্ঞান-প্রোফাইল',
  profileHave: 'এই দেশের ডেটা',
  profileChecked: 'দেখা হয়েছে, সীমানার ভেতরে কিছু নেই',
  profileContext: 'বৈশ্বিক প্রেক্ষাপট, এই দেশ নিয়ে নয়',
  profileEmpty: 'এই অ্যাপের কোনো ডেটা {name} কে ঢাকে না। বদলি কিছু না দেখিয়ে কিছুই দেখানো হচ্ছে না।',
  profilePick: 'কোন নাসা ডেটা আছে দেখতে একটি দেশ বাছুন।',
  profileRange: 'পরিসর',
  profileStamp: 'উৎসের সর্বশেষ সময়চিহ্ন',
  profileExplore: 'এর শব্দ শুনুন',
  profileExploreNote: 'এই দেশের মাসিক তাপমাত্রার গল্পে ডেটা জুকবক্স খোলে।',
  profileCells: '{n}টি ভেতরে',
  profileMax: 'সবচেয়ে জোরালো {v} {u}',
  profileMean: '{n}টির গড়: {v} {u}',
  profileDays: '{n} দিনের ডেটা',
  profileNoCells: '{what}: সীমানার ভেতরে কোনো ঘর বা বিন্দু নেই',
  profileSparkTitle: 'প্রতিনিধি বিন্দুতে মাসিক জলবায়ু',
  profileSparkAlt: 'বার্ষিক গড় তাপমাত্রা {a} থেকে {b} °C, {from} থেকে {to}',
  profilePointOnly: 'নাসা POWER, {pt} এ প্রায় ৫০ কিমি একটি ঘর। পুরো দেশের গড় নয়।',
  profileLoadingPower: 'নাসা POWER থেকে মাসিক মান আনা হচ্ছে…',
  profileTable: 'মানের তালিকা',
  profileNone: 'নেই',
  jbStoriesNav: 'গল্প',
  jbLead: 'একটি ডেটা-গল্প বাছুন, এর আসল পর্যবেক্ষণের তারিখ ধরে এগোন, আর প্রতিটি মানের অর্থ পড়ুন। প্রতিটি সংখ্যার উৎস দেখানো আছে।',
  jbStories: 'ডেটা-গল্প',
  jbPrevStories: 'গল্পগুলো বাঁয়ে সরান',
  jbNextStories: 'গল্পগুলো ডানে সরান',
  jbNoStories: 'এই ফিল্টারে কোনো গল্প মেলেনি। সব দেখতে রিসেট চাপুন।',
  jbNowShowing: 'দেখানো হচ্ছে',
  jbPicture: 'ছবি',
  jbShow: 'দেখান',
  jbFilters: 'ফিল্টার',
  jbTimeline: 'সময়রেখা',
  jbStory: 'গল্প',
  jbReset: 'রিসেট',
  jbPeriod: 'সময়কাল',
  jbOnePeriod: 'এই গল্পে একটিই সময়কাল ({y})।',
  jbNoPeriod: 'সময়কাল বাছতে সময়-সারির একটি গল্প বাছুন।',
  jbFrom: 'থেকে',
  jbTo: 'পর্যন্ত',
  jbFirstYear: 'প্রথম বছর',
  jbLastYear: 'শেষ বছর',
  jbTopic: 'বিষয়',
  jbAll: 'সব',
  jbRegion: 'অঞ্চল',
  jbSource: 'উৎস',
  jbAllSources: 'সব উৎস',
  jbCountryNote: 'দেশের গল্পে একটি প্রতিনিধি বিন্দু (তাপমাত্রা, বৃষ্টি) আর সীমানার ভেতরের আগুনের ঘর ব্যবহার হয়।',
  jbCountryHint: 'দেশের নিজস্ব গল্প যোগ করতে একটি দেশ বাছুন।',
  jbCollectionsNote: 'আগের পূর্ণ প্লেয়ারগুলো, অপরিবর্তিত।',
  jbTimelineAll: '{n}টি পর্যবেক্ষণ। ↑ ↓ সরায়, Home ও End লাফ দেয়।',
  jbTimelineBuckets: '{n}টি পর্যবেক্ষণ, দলে ভাগ করা। → দল খোলে, ← বন্ধ করে।',
  jbTimelineLabel: 'পর্যবেক্ষণের তারিখ: {what}',
  jbBucketCount: '{n}টি মান',
  jbBucketGaps: '{n}টি নেই',
  jbActive: 'বর্তমান',
  jbGap: 'ডেটা নেই',
  jbGapsNote: '{n}টি অনুপস্থিত মান রেখায় ফাঁক হিসেবে আঁকা, ভরাট করা হয়নি।',
  jbNoValues: 'বাছাই করা সময়কালে এই সারিতে কোনো বৈধ মান নেই।',
  jbTime: 'সময়',
  jbChartAlt: '{what}, {from} থেকে {to}, {lo} থেকে {hi}।',
  jbCap: '{time}: {what} ছিল {v}।',
  jbCapGap: '{time}: {what}-এর কোনো মান নেই। ফাঁকটি খালি রাখা হয়েছে।',
  jbCapUp: '{from} থেকে {d} বেশি।',
  jbCapDown: '{from} থেকে {d} কম।',
  jbCapSame: '{from}-এর সমান।',
  jbPictureNoTimeline: 'এই গল্পটি একটি ছবি, তাই এর সময়রেখা নেই। বাঁ থেকে ডানে শুনতে ছবির প্লেয়ারে খুলুন।',
  jbSoundNote: 'এই ডেটার পূর্ণ প্লেয়ারটিও আছে।',
  jbOpenCollection: '{name}-এ শুনুন',
  jbPrev: 'আগের পর্যবেক্ষণ',
  jbNext: 'পরের পর্যবেক্ষণ',
  jbPosition: '{n}টির মধ্যে {i}',
  plSound: 'শব্দ',
  plPlay: 'চালান',
  plPause: 'বিরতি',
  plResume: 'আবার চালান',
  plStop: 'থামান',
  plSeek: 'সারিতে অবস্থান',
  plVolume: 'ভলিউম',
  plMute: 'নিঃশব্দ',
  plSpeed: 'গতি',
  plTimeMode: 'সময় বিন্যাস',
  plEven: 'সমান ধাপ',
  plProportional: 'আসল সময়ের ব্যবধান',
  plTimeNote: 'সমান ধাপে প্রতিটি মান সমান লম্বা। আসল সময়ের ব্যবধানে তারিখ দূরে হলে মাঝে নীরবতা থাকে।',
  plCompare: 'দুটি সময়কাল তুলনা করুন',
  plCompareA: 'A হলো ফিল্টারে বাছাই করা সময়কাল: {p}।',
  plCompareB: 'সময়কাল B',
  plLayout: 'বিন্যাস',
  plSplit: 'A বাঁ কানে, B ডান কানে',
  plSequence: 'আগে A, তারপর B',
  plCompareNote: 'দুটিতেই একই ম্যাপিং, তাই B উঁচু শোনালে এর মানও বেশি।',
  plCompareNeedsYears: 'সময়কাল তুলনা করতে এই গল্পে অন্তত দুটি বছর লাগে।',
  plNote: 'এই শব্দ ডেটার সনিফিকেশন, রেকর্ডিং নয়। প্লে চাপলেই কেবল শুরু হয়।',
  plState: 'প্লেয়ার: {s}',
  plState_idle: 'লোড হয়নি',
  plState_loading: 'ডেটা লোড হচ্ছে',
  plState_ready: 'প্রস্তুত',
  plState_playing: 'চলছে',
  plState_paused: 'বিরতিতে',
  plState_ended: 'শেষ',
  plState_error: 'ত্রুটি',
  plNoSound: 'এই গল্পটি একটি ছবি, তাই এখানে বাজানোর মতো সারি নেই।',
  lgTitle: 'আপনি যা শুনছেন',
  lgRange: 'এই ডেটাসেটের নির্দিষ্ট পরিসর: {lo} (সবচেয়ে নিচু সুর, G3) থেকে {hi} (সবচেয়ে উঁচু সুর, G5)।',
  lgRangeOwn: 'এই সারির নিজস্ব পরিসর: {lo} থেকে {hi}।',
  lgNote: '{v} → {note} ({hz} Hz)',
  lgPitch: 'সুরের উচ্চতা: নির্দিষ্ট পরিসরের {pct}% ওপরে।',
  lgClippedHigh: 'পরিসরের ওপরে, তাই সবচেয়ে উঁচু সুর বাজে।',
  lgClippedLow: 'পরিসরের নিচে, তাই সবচেয়ে নিচু সুর বাজে।',
  lgPulses: 'স্পন্দন: ৬টির মধ্যে {n}টি, {from} থেকে {d} পরিবর্তনের জন্য।',
  lgPulsesFirst: 'স্পন্দন: ১টি। তুলনার জন্য আগের কোনো মান নেই।',
  lgTimbreWarm: 'সুরের রং: উষ্ণ ত্রিভুজ-তরঙ্গ, {b} ভিত্তির সমান বা ওপরে।',
  lgTimbreSoft: 'সুরের রং: নরম সাইন, {b} ভিত্তির নিচে।',
  lgTimbrePlain: 'সুরের রং: সাধারণ সাইন। এই ডেটাসেটের কোনো ভিত্তি নেই।',
  lgSilence: 'নীরবতা: এখানে কোনো মান নেই, ফাঁকটি ভরাট করা হয়নি।',
  lgNoCursor: 'কেমন শোনায় পড়তে সময়রেখায় একটি বিন্দু বাছুন।',
  lgLive: '{cap} শব্দ: {note}, {n}টি স্পন্দন।',
  topic_temperature: 'তাপমাত্রা',
  topic_greenhouse: 'গ্রিনহাউস গ্যাস',
  topic_ice: 'সামুদ্রিক বরফ',
  topic_ocean: 'সমুদ্রের তাপ',
  topic_fire: 'আগুন',
  topic_rain: 'বৃষ্টি',
  topic_agriculture: 'ফসল',
  region_global: 'বৈশ্বিক',
  region_bangladesh: 'বাংলাদেশ',
  region_country: 'দেশ',
  topicsTitle: 'পৃথিবীর বিষয়',
  topicsLead: 'ডেটায় ঢোকার ছয়টি পথ। প্রতিটি ডেটা জুকবক্সে একটি আসল গল্প খোলে।',
  topicSkip: 'অ্যানিমেশন বাদ দিন',
  topicPrev: 'আগের বিষয়',
  topicNext: 'পরের বিষয়',
  topicOf: '{n}টির মধ্যে বিষয় {i}: {name}',
  topicMore: 'কাছ থেকে দেখুন',
  topicImmersive: 'পূর্ণ দৃশ্য',
  topicBack: 'ফিরে যান',
  topicListen: 'জুকবক্সে খুলুন',
  topicSparkAlt: 'আসল মানের রেখা: {what}',
  topicLine_temperature: 'পৃথিবী ১৮০০ সালের শেষ দিকের চেয়ে প্রায় ১.৩ °C উষ্ণ।',
  topicLine_greenhouse: 'মাপা শুরুর পর থেকে বাতাসে CO₂ প্রতি বছর বেড়েছে।',
  topicLine_ocean: 'বাড়তি তাপের বেশির ভাগ সমুদ্রে জমা থাকে।',
  topicLine_ice: 'আর্কটিকের গ্রীষ্মের বরফ এখন ১৯৭৯-এর চেয়ে অনেক কম সাগর ঢাকে।',
  topicLine_fire: 'স্যাটেলাইট প্রতিদিন পৃথিবীর সবচেয়ে জোরালো আগুন দেখে।',
  topicLine_rain: 'বর্ষার বৃষ্টি সমানভাবে নয়, দমকে দমকে আসে।',
  topicDetail_temperature: 'নাসা GISS হাজারো স্থল স্টেশন ও সমুদ্রের পরিমাপ মিলিয়ে প্রতি বছরের একটি বৈশ্বিক মান দেয়, ১৯৫১–১৯৮০ গড় থেকে পার্থক্য হিসেবে।',
  topicDetail_greenhouse: 'মাউনা লোয়া রেকর্ড হাওয়াইয়ে বাতাসে মাপা CO₂-এর বার্ষিক গড়, সবচেয়ে দীর্ঘ সরাসরি রেকর্ড। ছবিটি আর্থ ইনফরমেশন সেন্টারের গ্রিনহাউস গ্যাস সূচক।',
  topicDetail_ocean: 'আর্থ ইনফরমেশন সেন্টারের চার্টে ১৯৫৭ থেকে সমুদ্রে যোগ হওয়া তাপ, জেটাজুলে। এটি ছবি, তাই জুকবক্স একে সংখ্যা নয়, উৎসসহ দেখায়।',
  topicDetail_ice: 'প্রতিটি মান স্যাটেলাইট থেকে আর্কটিক সামুদ্রিক বরফের সেপ্টেম্বরের গড় বিস্তার, প্রতি বছরের সর্বনিম্ন বিন্দু।',
  topicDetail_fire: 'VIIRS ৩৭৫ মিটারে সক্রিয় আগুন শনাক্ত করে। স্ন্যাপশটে প্রতিদিনের সবচেয়ে জোরালো ২° ঘরগুলো রাখা হয়; গল্পটি সবচেয়ে জোরালোটি বাজায়।',
  topicDetail_rain: 'সিলেট বিভাগের বিন্দুতে নাসা POWER-এর দৈনিক বৃষ্টি, জুন থেকে অক্টোবর ২০২৬। ছবিটি GEOS আবহাওয়া মডেলের দৃশ্য, আলোকচিত্র নয়।',
  inspTitle: 'জায়গার বিবরণ',
  inspMeasured: 'মাপা মান',
  inspVsPrev: 'আগের দিনের তুলনায়',
  inspIntensity: 'শব্দের তীব্রতা (০ থেকে ১)',
  inspCoords: 'স্থানাঙ্ক',
  inspPan: 'স্টেরিও প্যান',
  inspLeft: '{n}% বামে',
  inspRight: '{n}% ডানে',
  inspCentre: 'মাঝখানে',
  inspTime: 'সময়',
  inspConf: 'শনাক্তের আস্থা',
  inspHow: 'এই মান কীভাবে শব্দ হয়',
  inspSource: 'সূত্র: {p}',
  inspPlay: 'এই জায়গাটি শুনুন',
  inspLat: 'অক্ষাংশ',
  inspLon: 'দ্রাঘিমাংশ',
  dataTitle: 'ডেটা ও পদ্ধতি',
  spin: 'ঘোরান',
  spinHint: 'গ্লোব ঘোরান',
  panels: 'প্যানেল',
  imgUnavailable: 'ছবি অফলাইনে পাওয়া যায়নি',
  frHigh: '▲ উঁচু',
  frLow: '▼ নিচু',
  frHighNote: 'ছবির ওপরের দিক = উঁচু সুর',
  frLowNote: 'নিচের দিক = নিচু সুর',
  frBright: 'উজ্জ্বল = জোরালো',
  frWarm: 'উষ্ণ রঙ = ঝংকার',
  frCool: 'শীতল রঙ = নরম',
  frOne: 'একটি ছবি',
  frMode: 'মোড',
  stop: 'থামান',
  year: 'বছর',
  unitMm: 'মিমি',
  bdLoadFail: 'বাংলাদেশের ডেটা লোড করা যায়নি।',
  bdMapLabel: '৮টি বিভাগীয় শহরসহ বাংলাদেশের মানচিত্র। {date} তারিখে সবচেয়ে বেশি বৃষ্টি {city}-এ।',
  bdCityLabel: '{city}: {mm} মিমি',
  bdCircle: 'বৃত্তের আকার = সেদিনের বৃষ্টি। কোনো শহরে ক্লিক করে তার মৌসুম দেখুন।',
  bdRainTitle: '{city}: দৈনিক বৃষ্টি, {year}',
  bdChartUnit: 'মিমি/দিন · নাসা POWER',
  bdChartLabel: '{city}-এর দৈনিক বৃষ্টি, {year}। সবচেয়ে বৃষ্টির দিনে {mm} মিলিমিটার।',
  bdDashed: 'ড্যাশ রেখা: ওই মাসের গড় দৈনিক বৃষ্টি, ২০০১–২০২০ (নাসা POWER জলবায়ু গড়)।',
  bdTotalLine: '{total} ({from}–{to} {year})। {city}: {mm} মিমি, {wettest} {day} ({max} মিমি)।',
  bdCredit: 'সূত্র: {src}। মানগুলো শহরের অবস্থানের মডেলভিত্তিক অনুমান (প্রায় ৫০ কিমি ঘর), বৃষ্টিমাপক যন্ত্রের রিডিং নয়।',
  bdYear: '{year}: {mm} মিমি',
  dmIntro: 'আপনি যা শোনেন সবই নাসার প্রকাশ্য সূত্র থেকে (সঙ্গে NOAA-র CO₂ ও NSIDC-র সমুদ্র-বরফ রেকর্ড, যা নাসা নিজেই তাদের Vital Signs পাতায় ব্যবহার করে)। কাঁচা অংশ ও যে স্ক্রিপ্ট দিয়ে অ্যাপের ফাইল তৈরি হয়, সবই রিপজিটরিতে আছে (`scripts/raw/`, `scripts/build-snapshots.mjs`)। কোনো মান হাতে লেখা বা মসৃণ করা হয়নি।',
  dmSampling: 'নমুনা নেওয়ার নিয়ম',
  dmToSound: 'শব্দে রূপান্তর',
  dmFireTitle: 'দাবানল',
  dmRainTitle: 'বৃষ্টি',
  dmOceanTitle: 'সমুদ্রের তাপ',
  dmOtherTitle: 'অন্য ট্র্যাক',
  dmStereoTitle: 'পৃথিবীর কোথায়, আর স্টেরিও মানে কী',
  dmFireSource: 'নাসা FIRMS, VIIRS S-NPP ৩৭৫ মিটার প্রায়-রিয়েলটাইম সক্রিয় আগুনের শনাক্তকরণ (বিনামূল্যের FIRMS ম্যাপ কী লাগে; `npm run fetch:firms`)।',
  dmFireSampling: 'বিশ্ব, ২–৭ অক্টোবর ২০২৬। শনাক্তকরণ ২° ঘরে ভাগ করা; মান হলো ঘরের সর্বোচ্চ অগ্নিবিকিরণ শক্তি (MW); সবচেয়ে জোরালো ৮০টি ঘর রাখা হয়েছে। অ্যাটলাস ২–৫ অক্টোবর চালায়, যে দিনগুলো সব দৈনিক স্তরে আছে।',
  dmFireSound: '`{f}`। মান বাড়লে কড়কড় শব্দ দ্রুত হয় (প্রতি সেকেন্ডে ৪–২০) আর ফিল্টার উজ্জ্বল হয় (৮০০–৩০০০ Hz)।',
  dmRainSource: 'নাসা POWER Daily API v2.10, `PRECTOTCORR` (MERRA-2 থেকে ত্রুটি-সংশোধিত বৃষ্টিপাত), মিমি/দিন।',
  dmRainSampling: '১০° বৈশ্বিক গ্রিড, ৫০° দক্ষিণ থেকে ৫০° উত্তরে ৩৯৬টি বিন্দু, সবই আনা হয়েছে। ২–৫ অক্টোবরে একদিনের সর্বোচ্চ বৃষ্টির ৪৮টি বিন্দু রাখা হয়েছে, তাই এই স্তর ভেজা জায়গার নমুনা, পূর্ণ বৃষ্টির মানচিত্র নয়। ফ্রেম জুকবক্সে পূর্ণ GPM IMERG বৃষ্টির ছবি আছে।',
  dmRainSound: '`{f}`। মান বাড়লে ফোঁটা ঘন হয় (প্রতি সেকেন্ডে প্রায় ৩–১৮) আর সুর চড়া হয় (৩৪০–৭০০ Hz)।',
  dmOceanSource: 'নাসা JPL MUR সমুদ্রপৃষ্ঠের তাপমাত্রার বিচ্যুতি, মাসিক (ERDDAP ডেটাসেট `jplMURSST41anommday`, NOAA CoastWatch), সেপ্টেম্বর ২০২৬।',
  dmOceanSampling: '১° গ্রিড, ৩২,০৯৫টি বৈধ সমুদ্র-ঘর। স্থল বা বরফের ৩° মধ্যে এবং ৫৮° অক্ষাংশের বাইরের ঘর বাদ। সবচেয়ে বেশি বিচ্যুত ৪০টি ঘর বাছা হয়েছে, একটির থেকে আরেকটি অন্তত ১২° দূরে, ফলে বিশ্বজুড়ে উষ্ণ ও শীতল দুই চরমই শোনা যায়।',
  dmOceanGlobal: 'সব বৈধ ঘরে ক্ষেত্রফল-ভারিত গড় বিচ্যুতি +{mean} °C, আর সমুদ্রের {pct}% স্বাভাবিকের চেয়ে উষ্ণ ছিল।',
  dmOceanSound: '১১০ Hz-এ একটানা গুনগুন, প্রতি ৩ °C বিচ্যুতিতে ৪ সেমিটোন সরে যায়; উজ্জ্বলতা ঠিক করে `{f}`। উষ্ণ ঘর গোলাপি, শীতল ঘর নীল। পণ্যটি মাসিক, তাই দিনে দিনে বদলায় না।',
  dmFramesKey: 'নাসার ছবির ফ্রেম',
  dmFramesBody: 'একই সপ্তাহের জন্য সরাসরি আনা নাসা GIBS (Worldview) WMS ছবি: VIIRS আসল রঙ, VIIRS তাপ-অস্বাভাবিকতা, GPM IMERG বৃষ্টির হার, MUR SST বিচ্যুতি, OMI NO₂, MODIS অ্যারোসল, MODIS NDVI, VIIRS রাতের আলো। কাঁটা পিক্সেলের উজ্জ্বলতা ও রঙ পড়ে, তাই এই ট্র্যাক ছবিটিকে শব্দ করে, মাপাজোখা করা মানকে নয়।',
  dmBdKey: 'বাংলাদেশ',
  dmBdBody: '৮টি বিভাগীয় শহরের নাসা POWER দৈনিক `PRECTOTCORR`, ১ জুন–৫ অক্টোবর ২০২৬ এবং ২০২৫-এর একই দিনগুলো, POWER-এর ২০০১–২০২০ মাসিক জলবায়ু গড়ের সঙ্গে তুলনা করা। প্রায় ৫০ কিমি ঘরের মডেলভিত্তিক অনুমান, বৃষ্টিমাপক যন্ত্রের রিডিং নয়।',
  dmVitalKey: 'পৃথিবীর প্রাণচিহ্ন',
  dmVitalBody: 'নাসা GISS GISTEMP v4 বৈশ্বিক বার্ষিক বিচ্যুতি (১৮৮০–২০২৫, ১৯৫১–১৯৮০-র তুলনায়); NOAA GML মাউনা লোয়া বার্ষিক CO₂ (১৯৫৯–২০২৫), নাসার Vital Signs পাতার রেকর্ড; NSIDC Sea Ice Index v4.0 আর্কটিকের সেপ্টেম্বরের বিস্তার (১৯৭৯–২০২৬; ২০২৫–২৬ প্রায়-রিয়েলটাইম)। কাঁচা ফাইল `scripts/raw/`-এ। "আপনার ডেটা" যেকোনো দুই-কলামের CSV ব্রাউজারেই চালায়।',
  dmPlaceKey: 'যেকোনো জায়গা',
  dmPlaceBody: 'গ্লোবে ক্লিক করলে সেই বিন্দুর জন্য সরাসরি নাসা POWER মাসিক API-কে জিজ্ঞেস করা হয় (T2M ও PRECTOTCORR, ১৯৮১–২০২৫) এবং বছরপ্রতি একটি সুর বাজে। প্রবণতা হলো ক্ষুদ্রতম বর্গের ঢাল। মানগুলো প্রায় ৫০ কিমি ঘরের মডেলভিত্তিক।',
  dmStereoBody: 'প্যান = দ্রাঘিমাংশ ÷ ১৮০, তাই ১৮০° পশ্চিম একেবারে বামে আর ১৮০° পূর্ব একেবারে ডানে। ৩ডি (HRTF) মোডে অক্ষাংশও শব্দকে ওপরে-নিচে তোলে। জায়গার নাম আসে Natural Earth দেশের আকার থেকে; সমুদ্রের ঘর পায় তার অববাহিকার নাম। ১২টি কণ্ঠের সীমা মিশ্রণ পরিষ্কার রাখে: চালু স্তরের সবচেয়ে জোরালো মানগুলোই আপনি শোনেন।',
  dmCredit: 'এটি স্বাধীন একটি স্পেস অ্যাপস এন্ট্রি, নাসার অফিসিয়াল পণ্য নয়। ছবি ও ডেটা সৌজন্যে নাসা ESDIS, FIRMS, LaRC POWER, JPL PO.DAAC (NOAA CoastWatch ERDDAP-এর মাধ্যমে), GISS ও GIBS। গ্লোবের টেক্সচার: three.js উদাহরণ মানচিত্র।',
  afmLabel: 'অডিও-ফার্স্ট পৃথিবী-বিজ্ঞান অনুসন্ধান মোড',
  afmList: 'পর্যবেক্ষণের তালিকা',
  afmListNote: 'এই দিনের প্রতিটি পর্যবেক্ষণ পড়ার মতো তালিকায়, স্ক্রিন রিডার ও কিবোর্ড ব্যবহারকারীদের জন্য। প্রতিটি সারি তার আসল অবস্থানে নিজের শব্দ বাজায়।',
  afmSwitch: 'ভিজুয়াল ৩ডি-তে যান',
  afmShow: 'দেখান:',
  afmFires: 'শুধু আগুন',
  afmPrecip: 'শুধু বৃষ্টি',
  afmOcean: 'শুধু সমুদ্রের তাপ',
  afmTab: 'Tab দিয়ে সারিতে যান, শুনতে Enter চাপুন',
  afmNow: 'এখন বাজছে',
  afmPlay: 'এই জায়গার শব্দ চালান',
  closePlace: 'জায়গা বন্ধ করুন',
  chooseCity: 'একটি শহর বাছুন',
  dayLabel: 'দিন',
  tourRegion: 'গাইডেড ট্যুর',
  tourNext: 'পরের ধাপ',
  tourEnd: 'ট্যুর শেষ করুন',
  mapLabel: 'পর্যবেক্ষণের বিশ্ব মানচিত্র। ফোকাস বিন্দু সরাতে তীর কী চাপুন, সবচেয়ে কাছের পর্যবেক্ষণ শুনতে Enter বা Space চাপুন।',
  zoomIn: 'বড় করুন',
  zoomOut: 'ছোট করুন',
  resetMap: 'মানচিত্র আগের অবস্থায় আনুন',
  nearestObs: 'সবচেয়ে কাছের পর্যবেক্ষণ:',
  frSeeEarthGov: 'earth.gov-এ দেখুন',
  frLive: 'নাসা GIBS থেকে সরাসরি, অ্যাটলাসের ডেটার একই সপ্তাহ',
  frThen: 'আগে ও এখন',
  frHow: 'ছবি কীভাবে শব্দ হয়',
  frChoose: 'একটি ছবি বাছুন',
  srcLine: 'সূত্র: {c}।',
  seriesLabel: 'ধারা',
  spaceAppsLogoAlt: 'নাসা স্পেস অ্যাপস চ্যালেঞ্জের লোগো',
};

export const STRINGS: Record<Lang, Partial<Record<StringKey, string>>> = { en, bn };

/** One place for number formatting, so a line never mixes ২০২৫ and 2025. Years pass `{ useGrouping: false }`. */
export function fmtNum(n: number, lang: Lang, opts?: Intl.NumberFormatOptions): string {
  try { return new Intl.NumberFormat(lang === 'bn' ? 'bn-BD' : 'en-US', opts).format(n); } catch { return String(n); }
}
